In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

1- Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

vektor: tek boyutlu bir array dir. matris: cok boyutludur. En az ic ice 2 array icerir.

2- 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [2]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
type(a)

numpy.ndarray

3- Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [3]:
b = np.zeros((10,10), dtype='int32')
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

4- Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [4]:
c = np.ones((10,10), dtype='float')
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5- Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [5]:
d = np.full((10,10),9, dtype='int32')
d

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)

6- 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [6]:
e = np.arange(5,25,3)
e

array([ 5,  8, 11, 14, 17, 20, 23])

7- -1 ile 1 arasinda 30 adet Array olusturunuz.

In [7]:
f = np.linspace(-1,1,30)
f

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8- 0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [8]:
g = np.random.randint(0,30,size=(5,6))
g

array([[ 4, 11, 24,  2, 11,  1],
       [21, 25,  5,  0, 17,  0],
       [20, 19, 19, 18, 13,  8],
       [23,  3,  2, 10, 17,  4],
       [19, 15, 25, 19, 16, 10]])

9- Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [9]:
h = np.eye(10)
h

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10- 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; eleman sayisini boyut bilgisini/sayisini satir X sutun bilgisini veri tipini numpy metodlariyla yazdiriniz.

In [10]:
j = np.random.randint(0,10,size=(5,10))
print(j)
print("eleman sayisi= ",j.size)
print("boyut bilgisi= ",j.ndim)
print("shape        = ",j.shape)
print("data type    = ",j.dtype)

[[6 3 1 7 3 9 2 9 4 3]
 [9 3 9 8 0 5 9 5 0 8]
 [3 3 7 7 0 5 3 5 4 2]
 [1 6 8 2 5 1 6 6 4 7]
 [7 6 1 9 0 5 3 2 2 4]]
eleman sayisi=  50
boyut bilgisi=  2
shape        =  (5, 10)
data type    =  int64


11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [11]:
k = np.random.randint(0,10,size=(3,4,7))
k

array([[[3, 7, 2, 0, 6, 2, 0],
        [6, 1, 4, 8, 3, 5, 0],
        [6, 6, 2, 4, 0, 8, 2],
        [2, 6, 6, 3, 1, 6, 8]],

       [[6, 6, 8, 9, 1, 4, 8],
        [9, 9, 4, 2, 7, 9, 3],
        [8, 2, 1, 8, 8, 2, 2],
        [3, 7, 6, 9, 7, 0, 0]],

       [[3, 3, 4, 6, 4, 3, 7],
        [3, 4, 0, 2, 1, 3, 6],
        [1, 9, 5, 7, 4, 8, 8],
        [8, 3, 7, 0, 9, 0, 2]]])

12- Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [12]:
l = np.arange(1,10)
l

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
l_new = l.reshape(3,3)
l_new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13- 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [14]:
z = np.array([11,12,13])
x = np.array([14,15,16])
v = np.array([17,18,19])
n = np.array([20,21,22])
np.concatenate([z,x,v,n])

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

14- 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [15]:
q = np.array([[1],[4]])

w = np.array([[3,3,3,3],
            [5,5,5,5]])

np.hstack([q,w])

array([[1, 3, 3, 3, 3],
       [4, 5, 5, 5, 5]])

15- Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis = 1 birlestirme islemini sutun olarak yapar. axis = 0 birlestirme islemini satir olarak yapar.

16- Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [16]:
r = np.array([[1,1,1],
              [2,2,2]])

t = np.array([[3,3,3],
            [4,4,4],
             [5,5,5]])

np.vstack([r,t])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

17- 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

In [17]:
y = [42, 22,  9, 59, 30, 39, 88, 95, 18,  7]
np.split(y,[2,4,6,8])

[array([42, 22]),
 array([ 9, 59]),
 array([30, 39]),
 array([88, 95]),
 array([18,  7])]

18- Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [18]:
u = np.random.randint(1,100,size=5)
u

array([80, 23, 76, 95, 52])

In [19]:
s = np.sort(u)
s

array([23, 52, 76, 80, 95])

In [20]:
s[::-1]

array([95, 80, 76, 52, 23])

In [21]:
for index, x in np.ndenumerate(s):
  print(index, x)

(0,) 23
(1,) 52
(2,) 76
(3,) 80
(4,) 95


19- 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [22]:
p = np.random.randint(100,size=20)
p

array([60, 31, 46, 85, 93,  1, 64, 87, 40, 20, 40, 18,  7,  4, 32,  1, 12,
       89, 20, 96])

In [23]:
print("Bu vektorun 3. 5. ve 7. elemanlari: ",p[2],',',p[4],',',p[6])

Bu vektorun 3. 5. ve 7. elemanlari:  46 , 93 , 64


20- 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [24]:
o = np.random.randint(1,100,10)
o

array([22, 93, 75, 91, 78, 86, 82, 97, 55, 87])

In [25]:
o[3] = 444
o

array([ 22,  93,  75, 444,  78,  86,  82,  97,  55,  87])

21- “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Diagonal Matrix: Köşegen haric tüm item lerin sıfır olduğu bir matristir. Trace of Matrix : Bir kare matrisin ana köşegenindeki elemanların toplamıdir.

22- 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [26]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
i[0,0],i[1,1],i[2,2],i[3,3],i[4,4]

(1.0, 1.0, 1.0, 1.0, 1.0)

23- 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [28]:
s = np.arange(10,20)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
s[3::]

array([13, 14, 15, 16, 17, 18, 19])

24- 10X10 luk bir matris olusturunuz ve ;
    3.satir ve 5.sutuna ulasiniz.
    5.sutunun tum satirlarina ulasiniz.
    Tum sutunlarin 2.satirlarina ulasiniz.
    tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
    satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
    satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
    sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
    5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [30]:
locate = np.random.randint(7,size=(10,10))
locate

array([[3, 5, 5, 1, 1, 2, 3, 6, 4, 4],
       [2, 3, 6, 6, 5, 6, 3, 0, 1, 6],
       [4, 6, 3, 5, 6, 2, 2, 2, 4, 4],
       [6, 3, 1, 3, 5, 6, 2, 1, 2, 3],
       [3, 0, 6, 0, 4, 5, 1, 6, 2, 0],
       [1, 2, 5, 4, 1, 5, 6, 5, 2, 5],
       [5, 2, 1, 4, 3, 3, 3, 2, 4, 6],
       [6, 6, 5, 6, 1, 4, 5, 3, 1, 6],
       [6, 4, 3, 6, 4, 0, 6, 3, 3, 0],
       [6, 2, 0, 1, 5, 5, 5, 4, 4, 5]])

In [31]:
print("3.satir: ",locate[2])
print("5.sutun: ",locate[:,4])
print("5.sutunun tum satirlari:",locate[0:,[4]])
print("Tum sutunlarin 2.satirlari:",locate[[1],0:])
print("tum sutunlarin 2 ile 7 arasindaki satirlari:",locate[3:7,0:10])
print("satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerler:",locate[2:5,3:7])
print("satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerler:",locate[5:,:4])
print("sutun indexi sadece 3, 6, 9 olan kolonlarin, tum satirlari:",locate[0:,[3,6,9]])
locate[5,5]=1975
print("5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistirin:",locate)

3.satir:  [4 6 3 5 6 2 2 2 4 4]
5.sutun:  [1 5 6 5 4 1 3 1 4 5]
5.sutunun tum satirlari: [[1]
 [5]
 [6]
 [5]
 [4]
 [1]
 [3]
 [1]
 [4]
 [5]]
Tum sutunlarin 2.satirlari: [[2 3 6 6 5 6 3 0 1 6]]
tum sutunlarin 2 ile 7 arasindaki satirlari: [[6 3 1 3 5 6 2 1 2 3]
 [3 0 6 0 4 5 1 6 2 0]
 [1 2 5 4 1 5 6 5 2 5]
 [5 2 1 4 3 3 3 2 4 6]]
satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerler: [[5 6 2 2]
 [3 5 6 2]
 [0 4 5 1]]
satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerler: [[1 2 5 4]
 [5 2 1 4]
 [6 6 5 6]
 [6 4 3 6]
 [6 2 0 1]]
sutun indexi sadece 3, 6, 9 olan kolonlarin, tum satirlari: [[1 3 4]
 [6 3 6]
 [5 2 4]
 [3 2 3]
 [0 1 0]
 [4 6 5]
 [4 3 6]
 [6 5 6]
 [6 6 0]
 [1 5 5]]
5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistirin: [[   3    5    5    1    1    2    3    6    4    4]
 [   2    3    6    6    5    6    3    0    1    6]
 [   4    6    3    5    6    2    2    2    4    4]
 [   6    3    1    3    5    6    2  

25- 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin; 20 den buyuk olan kac deger var. 30’dan kucuk kac deger var icerisinde 33 gecen kac deger var olusturulan arrayin tum elemanlarini 5 ile carpin. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [32]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [33]:
arr[arr>20].size

5

In [34]:
arr[arr<30].size

6

In [35]:
arr[arr==33].size

0

In [36]:
arr*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [37]:
arr[arr%2]

array([0, 5, 0, 5, 0, 5, 0, 5, 0, 5])

26- 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; ortalamasini aliniz. standart sapmasini aliniz. varyansini aliniz. median’ini aliniz. en kucuk degeri bulunuz. en buyuk degeri bulunuz.

In [38]:
ar = np.linspace(0,1,50)
ar

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [39]:
print("ortamala   : ",np.mean(ar))
print("standart s.: ",np.std(ar))
print("varyans    : ",np.var(ar))
print("median     : ",np.median(ar))
print("en kucuk d.: ",np.min(ar))
print("en buyuk d.: ",np.max(ar))

ortamala   :  0.5
standart s.:  0.2945075446869757
varyans    :  0.086734693877551
median     :  0.5
en kucuk d.:  0.0
en buyuk d.:  1.0


27- Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

pandas serileri farkli data typelari icerebilir. numpy arrayler ayni data typelari icerebilir.

28- Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [40]:
mySeri = pd.Series(["py","coder",'s',"class",4,0.1], index=('A','B','C','D','E','G'))
mySeri

A       py
B    coder
C        s
D    class
E        4
G      0.1
dtype: object

29- Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. 
(ornek: fransa:paris)

In [41]:
myDict = {'hollanda':'amsterdam','almanya':'berlin','fransa':'paris','italya':'roma','turkiye':'ankara'}

In [42]:
myS = pd.Series(myDict)
myS

hollanda    amsterdam
almanya        berlin
fransa          paris
italya           roma
turkiye        ankara
dtype: object

30- 10 elemanli random bir vektor olusturun.
    Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
    Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
    Serinin index sirasina gore 1. Elamanina ulasin.
    Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
    Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. 
    (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
    Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [43]:
myVector = np.random.randint(1,100,10)
myVector

array([84, 92, 58, 41, 70, 81,  2, 56, 66,  5])

In [44]:
mySer = pd.Series(myVector, index=('a','b','c','d','f','g','h','j','k','l'))
mySer

a    84
b    92
c    58
d    41
f    70
g    81
h     2
j    56
k    66
l     5
dtype: int64

In [45]:
print("Index ismine gore serinin 3. eleman                                   : ", mySer['c'])
print("Serinin index sirasina gore 1. Elamani                                : ", mySer[0])
print("Index ismine gore serinin 2. Ve 7. Elemanlari                         : ", mySer[['b','g']])
print("Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerler        : ", mySer['b':'g'])
print("Index sirasiyla serinin 4. indexinden son indexine kadar olan degerler: ", mySer['d':])

Index ismine gore serinin 3. eleman                                   :  58
Serinin index sirasina gore 1. Elamani                                :  84
Index ismine gore serinin 2. Ve 7. Elemanlari                         :  b    92
g    81
dtype: int64
Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerler        :  b    92
c    58
d    41
f    70
g    81
dtype: int64
Index sirasiyla serinin 4. indexinden son indexine kadar olan degerler:  d    41
f    70
g    81
h     2
j    56
k    66
l     5
dtype: int64


31- 2 adet 5 elemanli seri olusturun.
    Olusturdugunuz serileri birlestirin.
    Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
    Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [46]:
seri1 = pd.Series([1,2,3,4.0,1.5])
seri2 = pd.Series([5,6,7,88,99])
seri1, seri2

(0    1.0
 1    2.0
 2    3.0
 3    4.0
 4    1.5
 dtype: float64,
 0     5
 1     6
 2     7
 3    88
 4    99
 dtype: int64)

In [47]:
seri3 = pd.concat([seri1,seri2])
seri3

0     1.0
1     2.0
2     3.0
3     4.0
4     1.5
0     5.0
1     6.0
2     7.0
3    88.0
4    99.0
dtype: float64

In [48]:
seri3.index=range(1,11)
seri3

1      1.0
2      2.0
3      3.0
4      4.0
5      1.5
6      5.0
7      6.0
8      7.0
9     88.0
10    99.0
dtype: float64

# Master odev

Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. 
Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve 
istenilen matrisi print ile birlikte ekrana yazdiriniz... 

Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. 
Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. 
Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [49]:
import time
loop = 0
t1 = time.time()

while True:
    loop+=1
    matrix = [np.random.rand(5,5) for _ in range(2)]
    
    m1 = matrix[0]
    m2 = matrix[1]
    
    diag = abs(np.diag(m1-m2))
    if len(list(filter(lambda x: x>0.1, diag)))==0:
        break
        
t2 = time.time()
time_diff = t2-t1

In [50]:
loop

2588

In [51]:
m1

array([[0.3467607 , 0.37274485, 0.29324562, 0.51984931, 0.88486071],
       [0.69519547, 0.20972005, 0.18397371, 0.31407737, 0.96362853],
       [0.64852695, 0.43887692, 0.76384454, 0.58868643, 0.5047805 ],
       [0.51166819, 0.40682968, 0.57005654, 0.14120093, 0.11816405],
       [0.29069617, 0.40490864, 0.63006117, 0.43177459, 0.45575806]])

In [52]:
m2

array([[0.43745558, 0.40858683, 0.84269089, 0.85539948, 0.20958878],
       [0.06916861, 0.27965651, 0.53405198, 0.95213015, 0.14978842],
       [0.1449092 , 0.98385555, 0.80371444, 0.56214832, 0.13056313],
       [0.12204688, 0.75620386, 0.55977022, 0.22461203, 0.30133565],
       [0.46828151, 0.06412327, 0.06218394, 0.70388842, 0.47907488]])

In [53]:
time_diff

0.04867100715637207

In [54]:
diag

array([0.09069487, 0.06993647, 0.0398699 , 0.0834111 , 0.02331682])

In [55]:
list(filter(lambda x: x<0.1, diag))

[0.09069487416820399,
 0.06993646567105372,
 0.0398699039210505,
 0.08341109963047821,
 0.023316823325365776]