In [4]:
import numpy as np

In [ ]:
#S1-vektor=tek boyutlu liste 
#   matris=birden fazla boyutu olan liste

In [2]:
#S2-
a=[1,2,3,4,5,6,7,8,9,10]
b=np.array(a)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#S3-
np.zeros((10,10), dtype="int32")

In [ ]:
#S4-
np.ones((10,10), dtype="float32")

In [ ]:
#S5-
np.full((10,10),9, dtype='int32')

In [ ]:
#S6-
np.arange(5,25,3)

In [19]:
#S7-
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [10]:
#S8-
np.random.randint(0,30,(5,6))

array([[ 0, 12, 22,  7,  6, 27],
       [ 6, 29, 14, 11, 19, 10],
       [12, 11, 18, 11,  0, 15],
       [ 1, 18,  6, 10, 17, 17],
       [20, 24,  2, 10, 10, 29]])

In [ ]:
#S9-
np.eye(10)

In [20]:
#s-10
matris=np.random.randint(0,10,(5,10),dtype="int32")
matris

array([[2, 1, 1, 2, 7, 4, 8, 1, 9, 2],
       [4, 3, 5, 4, 1, 8, 1, 7, 7, 8],
       [0, 0, 9, 4, 6, 5, 7, 4, 7, 5],
       [3, 3, 6, 7, 0, 5, 3, 6, 2, 3],
       [6, 3, 0, 5, 9, 6, 5, 0, 3, 6]])

In [21]:
#s-10_1
matris.size

50

In [22]:
#s-10_2
matris.ndim

2

In [ ]:
#s-10_3
matris.shape

In [ ]:
#s-10_4
matris.dtype

In [ ]:
#S-11
ucboyut=np.random.randint(10,size=(3,3,7))
ucboyut

In [ ]:
#S-12
vektor=np.arange(1,10)
vektor

In [ ]:
#S-12
vektor.reshape(3,3)

In [ ]:
#S-13
a=np.array([1,2,3,])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.array([10,11,12])
np.concatenate([a,b,c,d])

In [ ]:
#S-14
vektor=np.random.normal(1,10,(2,1))
vektor


In [23]:
matris=np.random.normal(1,10,(2,3))
matris

array([[ -5.13201835,  10.17139387,  12.0335071 ],
       [-17.77147184, -20.64312055,  -8.40826529]])

In [ ]:
np.concatenate([vektor,matris], axis =1)

In [ ]:
#S-15
np.concatenate isleminde dikey ya da yatay birlestirme secme olanagi saglar.

In [ ]:
#S-16
x=np.random.randint(10,size=(3,2,7))
y=np.random.randint(10,size=(3,3,7))
x,y

In [ ]:
np.concatenate([x,y],axis=1)

In [ ]:
#s17-
listeon=np.array([9, 1, 0, 8, 5, 7,2,4,3,6])
a,b,c,d,e=np.split(listeon,[2,4,6,8])
a,b,c,d,e

In [ ]:
#s18-
randomarray=np.random.randint(10,size=(3,7))
x=np.sort(randomarray)
x

In [ ]:
x[0:2,[1,2]]

In [ ]:
#S19-
rvek=np.random.randint(20, size=21)
rvek

In [ ]:
a=[3,5,7]
rvek[a]

In [ ]:
#S20-
rvekon=np.random.randint(10, size=11)
rvekon


In [ ]:
rvekon[5]=100
rvekon

In [ ]:
#S21-
#Diogonal matrix=Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise Diogonal matris denir. 
[1 0 0
0 2 0
0 0 3]
#Trace of Matrix=asal kosegen uzerindeki elemanlariini toplamina denir.

In [24]:
#S-22
x=np.eye(5,5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
for i in range(len(x)):
    print(x[i][i])

1.0
1.0
1.0
1.0
1.0


In [ ]:
#S-23
z=np.arange(10,20)
z[3:]

In [28]:
onaon=np.arange(100).reshape(10,10)
onaon

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2

In [82]:
onaon[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [79]:
onaon[:,5]


array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [84]:
onaon[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [73]:
onaon[2:7]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [86]:
onaon[2:5,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46]])

In [88]:
onaon[5:,:4]

array([[50, 51, 52, 53],
       [60, 61, 62, 63],
       [70, 71, 72, 73],
       [80, 81, 82, 83],
       [90, 91, 92, 93]])

In [100]:
onaon[5,5]=1981
onaon

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54, 1981,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [103]:
#S25-
beser=np.arange(0,51,5)
beser

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [105]:
len(beser[(beser>20)])

6

In [106]:
len(beser[(beser<30)])

6

In [110]:
len(beser[(beser==33)])

0

In [109]:
beser*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250])

In [114]:
beser/2

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ])

In [27]:
#S-26
z=np.linspace(0,1)
z


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [18]:
z.mean()
np.mean(z)

0.5

In [19]:
np.median(z)

0.5

In [20]:
z.std()

0.2945075446869757

In [28]:
z.max()

1.0

In [30]:
z.min()

0.0

In [31]:
z.var()

0.086734693877551

In [2]:
import pandas as pd

In [5]:
#S28-
upperlet=pd.Series(data=[1,2,3.0,'pandas',5j],index=['A','B','C','D','E'])
upperlet

A         1
B         2
C       3.0
D    pandas
E        5j
dtype: object

In [7]:
#S-29
dict={
    'Turkiye':'Ankara',
    'Hollanda':'Amsterdam',
    'Almanya':'Berlin',
    'Ingiltere':'Londra',
    'Yunanistan':'Atina',
}
seridict=pd.Series(dict)
seridict

Turkiye          Ankara
Hollanda      Amsterdam
Almanya          Berlin
Ingiltere        Londra
Yunanistan        Atina
dtype: object

In [8]:
#S30-
ranVektor=np.random.randint(9, size=10)
ranVektor

array([8, 7, 5, 8, 1, 7, 1, 1, 2, 5])

In [18]:
alf=['a','b','c','d','e','f','g','l','m','n']
len(alf)
ranVektorSeri=pd.Series(data=(ranVektor[0:11]),index=alf)
ranVektorSeri

a    8
b    7
c    5
d    8
e    1
f    7
g    1
l    1
m    2
n    5
dtype: int32

In [14]:
ranVektorSeri.get('c')

5

In [15]:
ranVektorSeri['a']

8

In [33]:
ranVektorSeri.get(['a','f'])

a    8
f    7
dtype: int32

In [34]:
ranVektorSeri['b':'f']

b    7
c    5
d    8
e    1
f    7
dtype: int32

In [35]:
ranVektorSeri['e':]

e    1
f    7
g    1
l    1
m    2
n    5
dtype: int32

In [8]:
seria=np.arange(5)
serib=np.arange(6,11)
serib

array([ 6,  7,  8,  9, 10])

In [9]:
seria=pd.Series(seria)
serib=pd.Series(serib)

In [14]:
data=dict(low=seria,high=serib)
df=pd.DataFrame(data)
df


low  high
0    0     6
1    1     7
2    2     8
3    3     9
4    4    10

In [11]:
seri=pd.concat([seria,serib],ignore_index=True)
seri

0     0
1     1
2     2
3     3
4     4
0     6
1     7
2     8
3     9
4    10
dtype: int32