In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### 1. Numpy’da Vektor ve Matriksin farkini tek cumle ile ifade ediniz.
    # Numpy'da vektor tek boyutlu bir dizi iken, matriks 2 boyutlu bir diziyi ifade eder.

In [2]:
# 2) 10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np 

a = np.array([1,2,3,4,5,6,7,8,9,10])  
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 3) Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10, 10), dtype = 'int32')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [4]:
# 4) Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10), dtype = 'float')


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 5) Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10),9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
# 6) 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3) 

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# 7) -1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [8]:
# 8) 0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.random.randint(0,30, (5,6))

array([[15,  6, 12,  7, 11,  8],
       [10, 10, 20, 26, 29, 13],
       [23, 19, 27,  0, 17,  2],
       [27,  2, 19, 25, 13, 10],
       [25, 29, 15, 14, 27, 22]])

In [9]:
# 9) Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
#10) 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
    #eleman sayisini
    #boyut bilgisini/sayisini
    #satir X sutun bilgisini
    #veri tipini numpy metodlariyla yazdiriniz.

In [11]:
#10) 
a= np.random.randint(10, size=(5, 10), dtype='int64')
a

array([[6, 6, 6, 8, 4, 6, 8, 4, 7, 5],
       [2, 0, 3, 0, 5, 3, 7, 3, 8, 0],
       [7, 0, 9, 8, 9, 2, 7, 2, 7, 5],
       [5, 6, 3, 8, 6, 9, 3, 1, 3, 9],
       [4, 8, 3, 9, 3, 1, 5, 9, 2, 3]])

In [12]:
#10)
print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape) 
print("Toplam eleman sayisi =  ",a.size)
print("Veri tipi =  ",a.dtype)

Boyut sayisi =   2
satir, sutun bilgisi =   (5, 10)
Toplam eleman sayisi =   50
Veri tipi =   int64


In [13]:
#11) 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. 
    #(3 boyutlu bir matris olusturulacak)
a = np.random.randint(10, size = (3, 4, 7))
a
   

array([[[8, 7, 8, 8, 8, 1, 8],
        [4, 8, 7, 0, 9, 3, 3],
        [1, 5, 1, 0, 7, 6, 8],
        [7, 8, 0, 9, 7, 8, 0]],

       [[3, 1, 6, 2, 0, 1, 6],
        [8, 8, 8, 6, 6, 8, 8],
        [3, 8, 8, 2, 3, 8, 5],
        [4, 5, 4, 7, 7, 9, 2]],

       [[7, 5, 2, 0, 0, 0, 5],
        [6, 7, 7, 7, 0, 8, 4],
        [7, 4, 0, 9, 9, 6, 4],
        [0, 5, 1, 0, 9, 4, 4]]])

In [14]:
print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape) 
print("Toplam eleman sayisi =  ",a.size)
print("Veri tipi =  ",a.dtype)

Boyut sayisi =   3
satir, sutun bilgisi =   (3, 4, 7)
Toplam eleman sayisi =   84
Veri tipi =   int64


In [15]:
# 12) Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. 
   #(boyut sayisini degistirin.)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 12)
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 13) 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])
np.concatenate([a,b,c,d])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
# 14)  2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), 
  # bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
    
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([[7, 8, 9], 
              [10, 11, 12]])

np.concatenate([a,b],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

15) Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?
"axis=1" dersek sutuna gore islem yapar(silme, ekleme), icine birsey vermezsek otomatik "axis=0" satira gore islem yapar


In [19]:
# 16) Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
np.vstack([a,b])   # farkli boyutlu arraylari SATIR BAZLI birlestirme yapar

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [20]:
# 16) Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
a = np.array([[99],
              [99]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
           
np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [21]:
# 17) 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 
 #5 ayri array olusturunuz.
x = [1, 3, 5, 7, 9, 11, 14, 15, 17, 19]
np.split(x, [2,4,6,8])  
    
    

[array([1, 3]),
 array([5, 7]),
 array([ 9, 11]),
 array([14, 15]),
 array([17, 19])]

In [22]:
# 17) 
a,b,c,d,e = np.split(x,  [2,4,6,8]) 
print(a,b,c,d)

[1 3] [5 7] [ 9 11] [14 15]


In [23]:
# 18) Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
   # Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
x = [11, 3, 55, 17, 89, 51, 4, 45, 97, 9]
np.sort(x) 

array([ 3,  4,  9, 11, 17, 45, 51, 55, 89, 97])

In [24]:
# 19) 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
a = np.random.randint(10, size = 20) 
print (a)
print (a[2])
print (a[4])
print (a[6])

[2 9 6 3 5 5 5 3 0 4 2 2 2 9 8 0 0 2 5 7]
6
5
5


In [25]:
# 20) 10 elemanli random bir vektor olusturun, bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
a = np.random.randint(10, size = 10)
print (a)
a[3] = 15
print (a)


[9 4 1 1 7 3 2 9 6 4]
[ 9  4  1 15  7  3  2  9  6  4]


21) “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.
Kosegen matriks olarak adlandirilir, genellikle kare matrikstir,  köşegenin dışında kalan girişlerin tümü sıfır ve genellikle kare matris olan bir matrisdir, kosegen uzerindeki bilesenlerin toplamina matrisin izi (trace) denir.


In [26]:
# 22) 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
a = np.random.randint(10, size = (5, 5)) 
print (a)
print (a[0,0])
print (a[1,1])
print (a[2,2])
print (a[3,3])
print (a[4,4])

[[2 4 9 8 8]
 [4 5 3 1 5]
 [7 3 7 5 3]
 [9 6 5 2 3]
 [4 4 9 6 2]]
2
5
7
2
2


In [27]:
# 23) 10 ile 20 arasinda bir vektor olusturun. 3.indexten son indexe kadar olan degerleri yazdirin.
a = np.arange(10,20)
print (a)
print (a[2:])

[10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19]


24) 10X10 luk bir matris olusturunuz ve ;
-3.satir ve 5.sutuna ulasiniz. 
5.sutunun tum satirlarina ulasiniz. 
Tum sutunlarin 2.satirlarina ulasiniz. 
tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 

In [28]:
# 24)
a = np.random.randint(99, size = (10, 10))
print (a)
print (a[2,:])   #3.satira  ulasiniz. 
print (a[:,4])   #5.satira  ulasiniz. 
print (a[1,:]) #Tum sutunlarin 2.satirlarina ulasiniz.
print (a[1:6,:]) #tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 


[[81 14 32 34 30 61 59  1 79 90]
 [83 59 63 58 33 19 45 62 30 45]
 [57  1 22 29 44 38 69  6 78 81]
 [98 19  7 86 34 48 89 40 90  6]
 [ 6 20 88  1 39 92 35 95 10  6]
 [75 48 67 91 16 96 98 60 59 55]
 [61 93 20 69 87  1 51 90 19 32]
 [54 51 20 27 55 41 53 61 97 67]
 [63 90 94 46 45  8 89 83 47 67]
 [ 0 65 40 31 37 34 40  2 57 53]]
[57  1 22 29 44 38 69  6 78 81]
[30 33 44 34 39 16 87 55 45 37]
[83 59 63 58 33 19 45 62 30 45]
[[83 59 63 58 33 19 45 62 30 45]
 [57  1 22 29 44 38 69  6 78 81]
 [98 19  7 86 34 48 89 40 90  6]
 [ 6 20 88  1 39 92 35 95 10  6]
 [75 48 67 91 16 96 98 60 59 55]]


In [29]:
# 24) satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
print (a[1:4,2:6])  

[[63 58 33 19]
 [22 29 44 38]
 [ 7 86 34 48]]


In [30]:
# # 24) satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
print (a)
print (a[4:,:3])  

[[81 14 32 34 30 61 59  1 79 90]
 [83 59 63 58 33 19 45 62 30 45]
 [57  1 22 29 44 38 69  6 78 81]
 [98 19  7 86 34 48 89 40 90  6]
 [ 6 20 88  1 39 92 35 95 10  6]
 [75 48 67 91 16 96 98 60 59 55]
 [61 93 20 69 87  1 51 90 19 32]
 [54 51 20 27 55 41 53 61 97 67]
 [63 90 94 46 45  8 89 83 47 67]
 [ 0 65 40 31 37 34 40  2 57 53]]
[[ 6 20 88]
 [75 48 67]
 [61 93 20]
 [54 51 20]
 [63 90 94]
 [ 0 65 40]]


In [31]:
# 24) sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
print (a)
print (a[:, [2, 5, 8]])

[[81 14 32 34 30 61 59  1 79 90]
 [83 59 63 58 33 19 45 62 30 45]
 [57  1 22 29 44 38 69  6 78 81]
 [98 19  7 86 34 48 89 40 90  6]
 [ 6 20 88  1 39 92 35 95 10  6]
 [75 48 67 91 16 96 98 60 59 55]
 [61 93 20 69 87  1 51 90 19 32]
 [54 51 20 27 55 41 53 61 97 67]
 [63 90 94 46 45  8 89 83 47 67]
 [ 0 65 40 31 37 34 40  2 57 53]]
[[32 61 79]
 [63 19 30]
 [22 38 78]
 [ 7 48 90]
 [88 92 10]
 [67 96 59]
 [20  1 19]
 [20 41 97]
 [94  8 47]
 [40 34 57]]


In [32]:
# 24) 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
print (a)
a[4,4] = 1974
print (a)

[[81 14 32 34 30 61 59  1 79 90]
 [83 59 63 58 33 19 45 62 30 45]
 [57  1 22 29 44 38 69  6 78 81]
 [98 19  7 86 34 48 89 40 90  6]
 [ 6 20 88  1 39 92 35 95 10  6]
 [75 48 67 91 16 96 98 60 59 55]
 [61 93 20 69 87  1 51 90 19 32]
 [54 51 20 27 55 41 53 61 97 67]
 [63 90 94 46 45  8 89 83 47 67]
 [ 0 65 40 31 37 34 40  2 57 53]]
[[  81   14   32   34   30   61   59    1   79   90]
 [  83   59   63   58   33   19   45   62   30   45]
 [  57    1   22   29   44   38   69    6   78   81]
 [  98   19    7   86   34   48   89   40   90    6]
 [   6   20   88    1 1974   92   35   95   10    6]
 [  75   48   67   91   16   96   98   60   59   55]
 [  61   93   20   69   87    1   51   90   19   32]
 [  54   51   20   27   55   41   53   61   97   67]
 [  63   90   94   46   45    8   89   83   47   67]
 [   0   65   40   31   37   34   40    2   57   53]]


25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
-20 den buyuk olan kac deger var.
-30’dan kucuk kac deger var
-icerisinde 33 gecen kac deger var
-olusturulan arrayin tum elemanlarini 5 ile carpin.
-olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [33]:
# 25)
v = np.arange(0, 50, 5)  
print (v)
print (np.sum(v > 20))
print (np.sum(v < 30))
print (np.sum(v < 30))
print (np.any(v == 33))
print (v == 33)
print (v *5)
print (v % 2)

[ 0  5 10 15 20 25 30 35 40 45]
5
6
6
False
[False False False False False False False False False False]
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


# 26) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
orlamasini aliniz.
standart sapmasini aliniz.
varyansini aliniz.
median’ini aliniz.
en kucuk degeri bulunuz.
en buyuk degeri bulunuz.

In [34]:
# 26)
a = np.linspace(0,1,50)
print (a)
print (np.std(a))
print (np.var(a))
print (np.median(a)) 
print (np.min(a))
print (np.max(a))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
0.2945075446869757
0.086734693877551
0.5
0.0
1.0


# 27- Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.
Ikisi arasındaki fark, veri yapılarında, bellek tüketiminde ve kullanım amaclarinda bulunmaktadir.

- NumPy sayısal verilerle çalışırken, Pandas tablo verileriyle çalışır.
- Pandas'daki veri yapısı Seriler, Veri Çerçeveleri ve Paneldir. Oysa NumPy, n boyuta kadar çıkabilen dizilere sahiptir.
- NumPy, Pandasa kıyasla daha az bellek tüketir.
- Pandas, 500.000 veya daha fazla satır içeren verilerle daha iyi performans gösterirken NumPy 50.000 veya daha az satır için daha iyi performans gösterir.
- Pandas, endüstride NumPy'den daha yaygın olarak kullanılmaktadır.

In [35]:
# 28) Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.
import numpy as np
import pandas as pd
seri4 = pd.Series(["Ahmet"," ",3, 4.6, None], index = ('A','B','C','D', 'E' ))    
seri4


A    Ahmet
B         
C        3
D      4.6
E     None
dtype: object

In [36]:
# 29) Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup 
    # onu seriye ceviriniz. (ornek: fransa:paris)

sozluk = { "Rusya" : 'Moskova', "Fransa" : 'Paris', "Iran" : 'Tahran', "Italya" : 'Roma', "Irak" : 'Bagdat'}    #sozluk uzerinden index atayacagiz.
print (sozluk)
seri5 = pd.Series(sozluk)
print (seri5)
    

{'Rusya': 'Moskova', 'Fransa': 'Paris', 'Iran': 'Tahran', 'Italya': 'Roma', 'Irak': 'Bagdat'}
Rusya     Moskova
Fransa      Paris
Iran       Tahran
Italya       Roma
Irak       Bagdat
dtype: object


# 30) 10 elemanli random bir vektor olusturun.

Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)

Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)

Serinin index sirasina gore 1. Elamanina ulasin.

Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)

Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)

Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

2 adet 5 elemanli seri olusturun.

Olusturdugunuz serileri birlestirin.

Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.

Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [37]:
# 30) 
npa = np.random.randint(0,30, 10)
print (npa)
seri = pd.Series((npa), index = ('a','b','c','d','e', 'f', 'g','h','i','j'))
print (seri)
print (seri["c"])
print (seri[1])
print (seri[["b","g"]])
print (seri["b":"g"])
print (seri[3:])

[12 24 29 29 27 16 19 24  0  8]
a    12
b    24
c    29
d    29
e    27
f    16
g    19
h    24
i     0
j     8
dtype: int64
29
24
b    24
g    19
dtype: int64
b    24
c    29
d    29
e    27
f    16
g    19
dtype: int64
d    29
e    27
f    16
g    19
h    24
i     0
j     8
dtype: int64


In [38]:
# 30) 2 adet 5 elemanli seri olusturun, Olusturdugunuz serileri birlestirin. 
    # Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
    #Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.
seri1 = pd.Series([1,2,3,4,5])
seri2 = pd.Series([6,7,8,9,10])
seri = pd.concat([seri1, seri2])
print (seri)
seri = pd.concat([seri1, seri2], ignore_index=True) 
print (seri)
print (seri.loc['4':'6'])
print (seri.iloc[4:7])
                  



0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
4    5
5    6
6    7
dtype: int64
4    5
5    6
6    7
dtype: int64


# Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [43]:
import time
trial=0
t1 = time.time()

while True:
    m1 = np.random.rand(10,10)
    m2 = np.random.rand(10,10)
    ds = np.diag(m1-m2)
    trial+=1
    if (np.all((ds > -0.1) & (ds < 0.1)))==True:
        t2=time.time()
        break
print (ds)
print ("Number of trials;", trial)
print ("Duration:", t2-t1, "seconds")        


[-0.08215052 -0.03017887  0.05277946 -0.03566067  0.01634416  0.02336115
  0.05611958  0.06266278  0.02415001 -0.09331156]
Number of trials; 4654020
Duration: 69.50800895690918 seconds
