In [ ]:
# Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

# Vektor cok boyutlu(N) iken matrisler 2 boyutludur. 

In [1]:
#  1 - 10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np

a = [1,2,3,4,5,6,7,8,9,10]

arr = np.array(a)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# 3 - Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

a = np.zeros([10,10], dtype='i')
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [7]:
# 4 - Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

a = np.ones([10,10], dtype='f')
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [9]:
# 5 - Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

a = np.full([10,10], 9, dtype='f')
a

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]], dtype=float32)

In [16]:
# 6 - 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

a = np.arange(5,25,3)
a

array([ 5,  8, 11, 14, 17, 20, 23])

In [18]:
# 7 - -1 ile 1 arasinda 30 adet Array olusturunuz.

a = np.linspace(-1,1, 30)
a

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [19]:
# 8 - 0 ile 30 arasinda 5x6’lik bir matris olusturun.

a = np.arange(0,30).reshape(5,6)
a


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
# 9 - Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

a = np.eye(10)
np.fill_diagonal(np.flipud(a), [1]*10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
# 10 - 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

a = np.random.randint(0, 10,50).reshape(5,10)

print(a)
print('ndim', a.ndim)
print('size', a.size)
print('shape', a.shape)
print('dtype', a.dtype.name)

[[0 2 7 8 8 5 8 3 9 2]
 [3 0 1 8 3 8 7 6 8 7]
 [2 4 9 0 4 2 4 5 4 5]
 [6 3 4 1 7 9 9 4 3 8]
 [7 6 3 9 5 7 6 0 4 2]]
ndim 2
size 50
shape (5, 10)
dtype int32


In [53]:
# 11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

a = np.random.randint(0,10,28*3).reshape(3,4,7)
a

array([[[6, 3, 3, 5, 1, 4, 6],
        [4, 5, 2, 4, 1, 8, 9],
        [4, 6, 0, 2, 3, 8, 3],
        [4, 1, 2, 6, 9, 0, 0]],

       [[6, 6, 0, 4, 0, 1, 9],
        [2, 7, 5, 3, 5, 7, 2],
        [9, 4, 2, 2, 7, 2, 6],
        [5, 2, 0, 7, 1, 9, 2]],

       [[6, 4, 5, 1, 4, 3, 3],
        [7, 7, 0, 9, 7, 5, 9],
        [1, 1, 9, 0, 1, 3, 2],
        [6, 5, 1, 3, 7, 3, 2]]])

In [56]:
# 12 - Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# 13 - 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([11,12,13])
d = np.array([21,22,23])


arr = np.concatenate([a,b,c,d])
arr

array([ 1,  2,  3, 10, 20, 30, 11, 12, 13, 21, 22, 23])

In [86]:
# 14 - 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak 
# sutun bazli birlestiriniz,

a = np.arange(4)
b = np.arange(20).reshape(4,5)
# arr = np.concatenate((b,a), axis=0)
# arr

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(a.ndim, b.ndim)


2 2


In [ ]:
# 15 - Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

# axis degeri 1e esitken column, 0 iken rowlari belirtir.

In [105]:
# 16 - Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

a = np.arange(3)
b = np.arange(9).reshape(3,3)

arr = np.vstack([a,b])

arr

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
# 17 -  10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

a = np.arange(10)
b = np.split(a, [0,3,5])
b

[array([], dtype=int32),
 array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9])]

In [150]:
# 18 - Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra 
# hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

a = np.random.randint(8, size=4)
b=np.sort(a)
for i in range(len(b)):
    print (b[::-1][i], 'index', i)
b[::-1]


7 index 0
6 index 1
3 index 2
0 index 3


array([7, 6, 3, 0])

In [159]:
# 19 -  20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

a = np.random.randint(0,20,size=20)
print(a[3],a[5],a[7],'\n',a)

13 13 16 
 [15 16 12 13 13 13 19 16  9 10 17  9 16 11  4 14 10 12 19  6]


In [ ]:
# 20 - “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu 
# belirten kucuk bir aciklama yaziniz.



# diagonal matrix, kosegeni disindaki degerlerin 0 oldugu kare matrixdir.
# trace matrix ise diagonal matrixdeki degerlerin toplanmasiyla elde edilen degerdir.

In [163]:
# 21 - 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

a = np.arange(25).reshape(5,5)
print(a)
print(a[0,0])
print(a[1,1])
print(a[2,2])
print(a[3,3])
print(a[4,4])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
6
12
18
24


In [167]:
#  22 - 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

a = np.arange(10,20)
print(a)
a[3:]

[10 11 12 13 14 15 16 17 18 19]


array([13, 14, 15, 16, 17, 18, 19])

In [181]:
# 24 - 10X10 luk bir matris olusturunuz ve ;
# 5.satir ve 5.sutuna ulasiniz.
# sutunun tum satirlarina ulasiniz.
# Tum sutunlarin 2.satirlarina ulasiniz.
# tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
# satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
# satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
# sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
# 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

a = np.arange(100).reshape(10,-1)
print(a,'\n')
print(a[4,4],'\n')
print(a[:,3],'\n')
print(a[2:7,:],'\n')
print(a[2:5,3:7],'\n')
print(a[5:,:4],'\n')
print(a[:,(3,6,9)],'\n')
a[5,5]=1986
print(a[5,5],'\n')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 

44 

[ 3 13 23 33 43 53 63 73 83 93] 

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]] 

[[23 24 25 26]
 [33 34 35 36]
 [43 44 45 46]] 

[[50 51 52 53]
 [60 61 62 63]
 [70 71 72 73]
 [80 81 82 83]
 [90 91 92 93]] 

[[ 3  6  9]
 [13 16 19]
 [23 26 29]
 [33 36 39]
 [43 46 49]
 [53 56 59]
 [63 66 69]
 [73 76 79]
 [83 86 89]
 [93 96 99]] 

1986 



In [211]:
# 25 -  0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki 
# islemleri uygulayin;
# 20 den buyuk olan kac deger var.
# 30’dan kucuk kac deger var
# icerisinde 33 gecen kac deger var
# olusturulan arrayin tum elemanlarini 5 ile carpin.
# olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
# olustural arrayin icerisinde, sadece sutunlara bakarak her bir sutunu toplayin ve toplami 30 dan buyuk kac sutun var
# olustural arrayin icerisinde, sadece satirlara bakarak her bir satiri toplayin ve toplami 30 dan buyuk kac satir var.

a = np.linspace(0,50,11, dtype='i')
print(a)
b=a>20
count=0
for i in b:
    if i==True:
        count+=1
print(count)

c=a<30
count1=0
for i in c:
    if i==True:
        count1+=1
print(count1)

count2=0
for i in c:
    if i==33:
        count2+=1
print(count2)

print(a*5)
print(a%2)

[ 0  5 10 15 20 25 30 35 40 45 50]
6
6
0
[  0  25  50  75 100 125 150 175 200 225 250]
[0 1 0 1 0 1 0 1 0 1 0]


In [216]:
# 26 - 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
# orlamasini aliniz.
# standart sapmasini aliniz.
# varyansini aliniz.
# median’ini aliniz.
# en kucuk degeri bulunuz.
# en buyuk degeri bulunuz.

a = np.linspace(0,1,50)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.max(a))
print(np.min(a))


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
0.5
0.2945075446869757
0.086734693877551
1.0
0.0


In [ ]:
# 27 - Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.


# pandas verileri farkli veri tiplerinden olusurken, numpy tek tip veri tipi vardir.
# Ayrica pandasda verilerin bir indexi vardir.


In [219]:
# 28 - Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.
import pandas as pd

a = pd.Series([0,1,2,"3",4], index=["A","B","C","D","E"])
a

A    0
B    1
C    2
D    3
E    4
dtype: object

In [225]:
# 29 - Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. 
# (ornek: fransa:paris)

a = {"Turkey":'Ankara','Nederland':'Amsterdam', "Duitsland":"Berlin","VS":"Washington","Engeland":"London"}
arr = pd.Series(a)
arr

Turkey           Ankara
Nederland     Amsterdam
Duitsland        Berlin
VS           Washington
Engeland         London
dtype: object

In [239]:
# 30  - 10 elemanli random bir vektor olusturun.
# Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
# Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
# Serinin index sirasina gore 1. Elamanina ulasin.
# Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
# Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
# Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

a = np.arange(10)
arr = pd.Series(a, index=['a',"b",'c','d','e','f','g','h','j','k'])
print(arr,'\n')
print(arr['c'],'\n')
print(arr[0],'\n')
print(arr[['b','g']],'\n')
print(arr['b':'g'],'\n')
print(arr['d':])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
j    8
k    9
dtype: int32 

2 

0 

b    1
g    6
dtype: int32 

b    1
c    2
d    3
e    4
f    5
g    6
dtype: int32 

d    3
e    4
f    5
g    6
h    7
j    8
k    9
dtype: int32


In [271]:
# 31 - 2 adet 5 elemanli seri olusturun.
# Olusturdugunuz serileri birlestirin.
# Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
# Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

a = pd.Series([1,2,3,4,5])
b = pd.Series([11,12,13,14,15])
arr = pd.concat([a,b])
print(arr)
arr.index=(range(1,11))
print(arr)
arr.iloc[3:6]

0     1
1     2
2     3
3     4
4     5
0    11
1    12
2    13
3    14
4    15
dtype: int64
1      1
2      2
3      3
4      4
5      5
6     11
7     12
8     13
9     14
10    15
dtype: int64


4     4
5     5
6    11
dtype: int64

In [ ]:
# 32 - Master odev ;
# Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
# Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris 
# bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen
# matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. 
#     Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz.
#     Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

import time
tstart = time.time()
count=0
while True:
    count+=1
    a = np.random.rand(20,20)
    b = np.random.rand(20,20)
    fark = np.diag(a-b)
    aa=0
    for i in fark:
        if i>0.1 or i<-0.1:
            break
        else:
            aa+=1
    if aa==20:
        break

print('diag',fark, 'count', count)

tfinish = time.time()
print('time',tfinish-tstart)


In [ ]:
# 32 - Master odev ;
# Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
# Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris 
# bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen
# matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. 
#     Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz.
#     Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

import time
tstart = time.time()
for k in range(2,12):
    count=0
    while True:
        count+=1
        a = np.random.rand(k,k)
        b = np.random.rand(k,k)
        fark = np.diag(a-b)
        aa=0
        for i in fark:
            if i>0.1 or i<-0.1:
                break
            else:
                aa+=1
        if aa==k:
            break

    print('diag',fark, 'count', count)

    tfinish = time.time()
    print('time',tfinish-tstart)


diag [-0.08349946 -0.06996534] count 25
time 0.0019986629486083984
diag [ 0.02070199 -0.05541427 -0.01089287] count 127
time 0.008996009826660156
diag [ 0.08646627 -0.03316665 -0.04104706 -0.09100083] count 729
time 0.04997062683105469
diag [-0.0391146   0.04947659  0.06165431  0.08524428  0.03669236] count 3838
time 0.17189431190490723
diag [ 0.05869352  0.08502774 -0.00658613 -0.08222649  0.01057412 -0.01010439] count 37173
time 0.7265498638153076
diag [ 0.01910559  0.0520021   0.00487154  0.08035674  0.0098468  -0.02341778
  0.01762266] count 190777
time 5.333693027496338
diag [-0.02608309  0.07017209  0.05618957 -0.08676231  0.06228886  0.07716268
  0.06225509 -0.02122949] count 170699
time 8.22889494895935
diag [ 0.02351848 -0.09810878  0.07194092 -0.08542211  0.04328498 -0.09900629
  0.05670616  0.07015854 -0.08084257] count 3629570
time 73.50219488143921
diag [-0.08058733 -0.05579832 -0.05767236 -0.06844673 -0.03627899 -0.05193965
  0.04115525 -0.05567166 -0.0728547   0.01869676