1- Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

Vektor tek boyutlu, matris ise 2 veya daha cok boyutludur.

2- 10 elemanli bir listeden NumPy Array’i olusturunuz.


In [1]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [2]:
np.zeros((10,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4- Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [3]:
np.ones((10,10), dtype = 'float')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5- Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [4]:
np.full((10,10), 9, dtype = 'int')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6- 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [5]:
a = np.arange(6,25,3)
a

array([ 6,  9, 12, 15, 18, 21, 24])

7 -1 ile 1 arasinda 30 adet Array olusturunuz.

In [6]:
np.linspace(-1, 1, 30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8- 0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [7]:
np.random.randint(0,30, (5,6))

array([[16, 15, 26,  9, 23, 28],
       [12, 19, 10, 25, 25, 13],
       [19, 16,  2, 28,  3, 24],
       [ 5,  8, 21,  9, 26,  6],
       [26, 29, 11,  3, 27, 19]])

9- Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [8]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10- 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

* eleman sayisini
* boyut bilgisini/sayisini
* satir X sutun bilgisini
* veri tipini numpy metodlariyla yazdiriniz.

In [9]:
b = np.random.randint(0,10, (5,10))
print(b)
print("eleman sayisi= ",b.size)
print("boyut bilgisi= ",b.ndim)
print("satirxsutun bilgisi= ",b.shape)
print("data type    = ",b.dtype)

[[8 4 0 8 5 6 6 5 3 9]
 [4 4 4 3 0 0 3 0 8 5]
 [8 6 3 0 5 8 3 4 4 5]
 [7 7 5 1 1 8 0 0 3 8]
 [7 7 7 9 9 2 0 9 5 4]]
eleman sayisi=  50
boyut bilgisi=  2
satirxsutun bilgisi=  (5, 10)
data type    =  int32


11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [10]:
c = np.random.randint(0, 10, 3*4*7).reshape(3,4,7)
c

array([[[4, 2, 6, 1, 1, 6, 9],
        [8, 0, 6, 8, 6, 1, 3],
        [0, 3, 7, 0, 8, 8, 9],
        [9, 8, 7, 6, 7, 8, 6]],

       [[4, 3, 7, 7, 1, 2, 4],
        [7, 6, 8, 3, 3, 3, 2],
        [4, 0, 1, 3, 6, 6, 6],
        [8, 6, 5, 5, 7, 7, 1]],

       [[8, 9, 3, 3, 6, 8, 0],
        [7, 3, 7, 8, 7, 8, 7],
        [8, 7, 8, 8, 4, 9, 1],
        [0, 4, 0, 3, 7, 0, 9]]])

12- Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [11]:
d = np.arange(1,10)
d

new_d = d.reshape(3,3)
new_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13- 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.


In [12]:
x = np.array([0,1,2])
y = np.array([3,4,5])
z = np.array([6,7,8])
t = np.array([9,10,11])
np.concatenate([x,y,z,t])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

14- 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.

In [13]:
e = np.array([[1], [2]])
e

array([[1],
       [2]])

In [14]:
f = np.arange(3,11).reshape(2,4)
f

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [15]:
np.concatenate([e, f], axis=1)

array([[ 1,  3,  4,  5,  6],
       [ 2,  7,  8,  9, 10]])

15- Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis = 1 Sutun bazli birlestirme yapar. 
axis = 0 Satir bazli birlestirme yapar. 

16- Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [16]:
f1 = np.arange(0,3)
f1

array([0, 1, 2])

In [17]:
f2 = np.arange(4,13).reshape(3,3)
f2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.vstack([f1, f2])

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.hstack([f1.reshape(3,1),f2.T])

array([[ 0,  4,  7, 10],
       [ 1,  5,  8, 11],
       [ 2,  6,  9, 12]])

17- 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

In [20]:
x = np.arange(0,10)  # 10 elemanli bir liste olusturur.
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.split(x, 5) # 5 ayri array olusturur.

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

18- Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [22]:
v = np.random.randint(0,20,10)
v

array([ 4,  1,  6, 15, 18, 14, 18, 11,  3, 15])

In [23]:
y = np.sort(v)  # Kucukten buyuge siralar.
y

array([ 1,  3,  4,  6, 11, 14, 15, 15, 18, 18])

In [24]:
v_sorted = np.sort(v)[::-1]  # Buyukten kucuge siralar.
v_sorted

array([18, 18, 15, 15, 14, 11,  6,  4,  3,  1])

In [25]:
y[::-1]  # II. YOL(Buyukten kucuge siralar.)

array([18, 18, 15, 15, 14, 11,  6,  4,  3,  1])

In [26]:
for i in range(len(v_sorted)):
    print(f'{i}.indexte {v_sorted[i]} var')

0.indexte 18 var
1.indexte 18 var
2.indexte 15 var
3.indexte 15 var
4.indexte 14 var
5.indexte 11 var
6.indexte 6 var
7.indexte 4 var
8.indexte 3 var
9.indexte 1 var


19- 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [27]:
k = np.random.randint(0,50,20)
k

array([40, 24,  5, 22, 46,  8, 36, 43, 19, 26, 42, 39, 46, 13, 40,  1,  2,
       30,  1, 17])

In [28]:
k[3], k[5], k[7]

(22, 8, 43)

20- 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [29]:
l = np.random.randint(0,50,10)
l

array([26, 35, 20, 21, 35, 41, 11, 32, 15,  7])

In [30]:
l[4] = 100
l

array([ 26,  35,  20,  21, 100,  41,  11,  32,  15,   7])

21- “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Diagonal Matrix: Köşegen dışı girişlerinin tümü sıfıra eşit olan bir kare matristir.

Trace of Matrix: Basitçe bir kare Matris'in ana köşegenindeki ögelerin toplamıdır. Ana köşegen, sol üst köşeden başlayıp sağ alt köşede biten köşegendir.




22- 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [31]:
m = np.diag([5,6,7,8,9])
m

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9]])

In [32]:
m[0,0],m[1,1],m[2,2],m[3,3],m[4,4]

(5, 6, 7, 8, 9)

23- 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [33]:
n = np.arange(11,20)
n

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
n[3:]

array([14, 15, 16, 17, 18, 19])

24- 10X10 luk bir matris olusturunuz ve ;

* 3.satir ve 5.sutuna ulasiniz.
* 5.sutunun tum satirlarina ulasiniz.
* Tum sutunlarin 2.satirlarina ulasiniz.
* Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
* Satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
* Satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
* Sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
* 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [35]:
m1 = np.random.randint(100, size = (10, 10))
m1

array([[72, 86, 42, 50, 20, 87, 46, 56, 17, 45],
       [35,  4, 83, 23, 59, 99, 64, 81, 94, 73],
       [43,  5, 55, 31, 59, 13, 13, 31,  3, 93],
       [ 6, 77, 30, 71, 27, 40, 57, 86, 22, 44],
       [ 5,  8,  9, 90, 69, 17, 38,  8, 18, 18],
       [11, 66, 24,  1, 12, 65, 12, 47, 49, 38],
       [ 9, 96, 62, 30, 44, 64, 17, 93, 18, 24],
       [11, 98, 91, 92, 42, 66, 28, 29, 79,  4],
       [98, 76, 96,  5, 65, 26, 38, 76, 96, 35],
       [38, 17, 76, 94, 78, 29, 50, 35, 98,  4]])

In [36]:
m1[2,4]  #3.satir ve 5.sutuna ulasiniz.

59

In [37]:
m1[:,4]  # 5.sutunun tum satirlarina ulasiniz.

array([20, 59, 59, 27, 69, 12, 44, 42, 65, 78])

In [38]:
m1[1,:]  # Tum sutunlarin 2.satirlarina ulasiniz.

array([35,  4, 83, 23, 59, 99, 64, 81, 94, 73])

In [39]:
m1[2:7,:]  # Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.

array([[43,  5, 55, 31, 59, 13, 13, 31,  3, 93],
       [ 6, 77, 30, 71, 27, 40, 57, 86, 22, 44],
       [ 5,  8,  9, 90, 69, 17, 38,  8, 18, 18],
       [11, 66, 24,  1, 12, 65, 12, 47, 49, 38],
       [ 9, 96, 62, 30, 44, 64, 17, 93, 18, 24]])

In [40]:
m1[2:5,3:7]  # Satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.

array([[31, 59, 13, 13],
       [71, 27, 40, 57],
       [90, 69, 17, 38]])

In [41]:
m1[5:,:4]  # Satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.

array([[11, 66, 24,  1],
       [ 9, 96, 62, 30],
       [11, 98, 91, 92],
       [98, 76, 96,  5],
       [38, 17, 76, 94]])

In [42]:
m1[:,[3,6,9]]  # Sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.

array([[50, 46, 45],
       [23, 64, 73],
       [31, 13, 93],
       [71, 57, 44],
       [90, 38, 18],
       [ 1, 12, 38],
       [30, 17, 24],
       [92, 28,  4],
       [ 5, 38, 35],
       [94, 50,  4]])

In [43]:
m1[5,5] = 1981  # 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
m1

array([[  72,   86,   42,   50,   20,   87,   46,   56,   17,   45],
       [  35,    4,   83,   23,   59,   99,   64,   81,   94,   73],
       [  43,    5,   55,   31,   59,   13,   13,   31,    3,   93],
       [   6,   77,   30,   71,   27,   40,   57,   86,   22,   44],
       [   5,    8,    9,   90,   69,   17,   38,    8,   18,   18],
       [  11,   66,   24,    1,   12, 1981,   12,   47,   49,   38],
       [   9,   96,   62,   30,   44,   64,   17,   93,   18,   24],
       [  11,   98,   91,   92,   42,   66,   28,   29,   79,    4],
       [  98,   76,   96,    5,   65,   26,   38,   76,   96,   35],
       [  38,   17,   76,   94,   78,   29,   50,   35,   98,    4]])

25- 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

* 20 den buyuk olan kac deger var.
* 30’dan kucuk kac deger var
* icerisinde 33 gecen kac deger var
* olusturulan arrayin tum elemanlarini 5 ile carpin.
* olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.


In [44]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
arr[arr>20].size

5

In [46]:
arr[arr<30].size

6

In [47]:
arr[arr==33].size

0

In [48]:
arr*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [49]:
arr[arr%2]

array([0, 5, 0, 5, 0, 5, 0, 5, 0, 5])

26- 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;

* Ortalamasini aliniz.
* Standart sapmasini aliniz.
* Varyansini aliniz.
* Median’ini aliniz.
* En kucuk degeri bulunuz.
* En buyuk degeri bulunuz.

In [50]:
n = np.linspace(0,1,50)
n

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [51]:
n.mean()

0.5

In [52]:
n.std()

0.2945075446869757

In [53]:
n.var()

0.086734693877551

In [54]:
np.median(n)

0.5

In [55]:
n.min()

0.0

In [56]:
n.max()

1.0

27- Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

Pandas serilerde index sutunu da bulunur. Index belirtilmez ise default kabul edilir.
Pandas serileri farkli data type'larini da icerebilir. Numpy arrayler ayni data typelari icerebilir.

28- Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [57]:
import pandas as pd

seri = pd.Series(["Pandas",3,0.5,None," "], index = ('A','B','C','D','E'))
print(seri)

A    Pandas
B         3
C       0.5
D      None
E          
dtype: object


29- Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [58]:
dict = {"Netherlands ":'Amsterdam', "Japan":'Tokyo', "USA":'Washington', "Sweden":'Stockholm', "Norway":'Oslo'}

seri = pd.Series(dict)  # dict' i seriye donusturduk
seri

Netherlands      Amsterdam
Japan                Tokyo
USA             Washington
Sweden           Stockholm
Norway                Oslo
dtype: object

30- 10 elemanli random bir vektor olusturun.

* Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin 2. ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [59]:
p = np.random.randint(1,50,10)
p

array([25, 43, 17, 41,  1, 42, 10, 49,  7, 45])

In [60]:
seri = pd.Series(p, index = ('a','b','c','d','f','g','h','j','k','l'))
seri

a    25
b    43
c    17
d    41
f     1
g    42
h    10
j    49
k     7
l    45
dtype: int32

In [61]:
seri['c']

17

In [62]:
seri['a']

25

In [63]:
seri[['b','g']]

b    43
g    42
dtype: int32

In [64]:
seri['b':'g']

b    43
c    17
d    41
f     1
g    42
dtype: int32

In [65]:
seri['d':]

d    41
f     1
g    42
h    10
j    49
k     7
l    45
dtype: int32

31- 2 adet 5 elemanli seri olusturun. 

* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [66]:
seri1 = pd.Series(range(1,6))
seri1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [67]:
seri2 = pd.Series(list('abcde'))
seri2

0    a
1    b
2    c
3    d
4    e
dtype: object

In [68]:
seri3 = pd.concat([seri1, seri2])
seri3

0    1
1    2
2    3
3    4
4    5
0    a
1    b
2    c
3    d
4    e
dtype: object

In [69]:
seri3.index=range(1,11)
seri3

1     1
2     2
3     3
4     4
5     5
6     a
7     b
8     c
9     d
10    e
dtype: object

Master Odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [70]:
import time
loop = 0
t1 = time.time()

while True:
    loop+=1
    matrix = [np.random.rand(5,5) for _ in range(2)]
    
    m1 = matrix[0]
    m2 = matrix[1]
    
    diag = abs(np.diag(m1-m2))
    if len(list(filter(lambda x: x>0.1, diag)))==0:
        break
        
t2 = time.time()
time_diff = t2-t1

In [71]:
loop

996

In [72]:
m1

array([[0.36394498, 0.52762157, 0.44136464, 0.14587675, 0.62161837],
       [0.26598839, 0.67664033, 0.02094888, 0.17833102, 0.20847826],
       [0.47815234, 0.43525637, 0.57552832, 0.94421711, 0.80187408],
       [0.26476169, 0.29520753, 0.80075934, 0.0641034 , 0.5862547 ],
       [0.89661579, 0.10927276, 0.28762775, 0.06520436, 0.53892805]])

In [73]:
m2

array([[0.41422803, 0.00844265, 0.11352015, 0.36784237, 0.43202444],
       [0.11432663, 0.69389271, 0.57279233, 0.7328795 , 0.12453238],
       [0.05585718, 0.6938869 , 0.63879564, 0.08907328, 0.19229631],
       [0.12070616, 0.19247081, 0.37114802, 0.01405984, 0.6945751 ],
       [0.85513088, 0.88327624, 0.60285771, 0.31268734, 0.53909958]])

In [74]:
time_diff

0.031993865966796875

In [75]:
diag

array([0.05028305, 0.01725238, 0.06326732, 0.05004356, 0.00017153])

In [76]:
list(filter(lambda x: x<0.1, diag))

[0.05028305117233456,
 0.017252376820871773,
 0.06326732000715207,
 0.05004355989542297,
 0.00017152895628869125]