# Numpy ve Pandas ile ilgili Odev

1- Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

In [ ]:
# Vektor tek boyutlu, matris ise cok boyutludur.

2- 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [2]:
import numpy as np
list1= list(range(10))
a= np.array(list1)
print(list1)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


3- Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [10]:
np.zeros((10,10), dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4- Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [11]:
np.ones((10,10), dtype = 'float32')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

5- Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [15]:
np.full((10,10), 9, dtype = 'int32')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6- 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [18]:
a1= np.arange(6,25,3)
a1

array([ 6,  9, 12, 15, 18, 21, 24])

7- -1 ile 1 arasinda 30 adet Array olusturunuz.

In [19]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8- 0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [20]:
np.random.randint(0,30, (5,6)) 

array([[ 1, 23, 15, 15, 29, 23],
       [24, 23, 19, 17,  9, 28],
       [24, 20, 20, 12, 17, 20],
       [ 7, 21,  6, 21, 16, 27],
       [19, 16, 22, 10,  9, 18]])

9- Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10- 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

eleman sayisini

boyut bilgisini/sayisini

satir X sutun bilgisini

veri tipini numpy metodlariyla yazdiriniz.

In [24]:
a2=np.random.randint(0,10, (5,10))
print("Boyut sayisi =  ",a2.ndim) 
print("Satir X Sutun bilgisi =  ",a2.shape) 
print("Toplam eleman sayisi =  ",a2.size)
print("Veri tipi =  ",a2.dtype)

Boyut sayisi =   2
Satir X Sutun bilgisi =   (5, 10)
Toplam eleman sayisi =   50
Veri tipi =   int32


11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [27]:
a3=np.random.randint(0,10,(3,4,7))
a3

array([[[2, 4, 3, 9, 2, 6, 7],
        [0, 6, 1, 3, 6, 5, 8],
        [8, 7, 7, 1, 3, 7, 0],
        [8, 4, 5, 7, 1, 2, 0]],

       [[0, 5, 2, 2, 9, 8, 4],
        [7, 9, 4, 6, 8, 9, 7],
        [6, 5, 2, 0, 9, 8, 9],
        [7, 1, 9, 4, 2, 4, 4]],

       [[5, 1, 0, 8, 8, 3, 1],
        [4, 8, 2, 4, 0, 1, 3],
        [9, 8, 0, 9, 2, 2, 4],
        [1, 0, 1, 6, 8, 6, 4]]])

12- Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [34]:
a4= np.arange(0,9)
print(a4)
a5= a4.reshape(3,3)
print(a5)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


13- 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [42]:
x1 = np.arange(0,10)
print(x1)
y1 = np.arange(10,20)
print(y1)
z1 = np.arange(20,30)
print(z1)
z2 = np.arange(30,40)
print(z2)

z3= np.concatenate([x1,y1,z1,z2])
z3

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

14- 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [55]:
a5 = np.array([[1], [2]])
# print(a5)
b5 = np.array([[1,2],
              [3,4]])
# print(b5)              
np.concatenate([a5,b5], axis = 1)

array([[1, 1, 2],
       [2, 3, 4]])

15- Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

In [ ]:
# 1 birlestirme islemini yatay (sutun) olarak yapar  1 sutun, 0 ise dikey (satir) olarak.

16- Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [84]:
# a6 = np.array([1,2])

# b6 = np.array([[3,4], 
#               [5,6]])

# satir1=np.vstack([a6,b6])

# print (satir1)


a7 = np.array([[1],[2]])

b7 = np.array([[3,4],[5,6]])


sutun1=np.hstack([a7,b7])

print(sutun1)

[[1 3 4]
 [2 5 6]]


17- 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [86]:
x = list(range(10))
print(x)
a,b,c,d= np.split(x, [3,6,9]) 
print(a,b,c,d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2] [3 4 5] [6 7 8] [9]


18- Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [104]:
a8= np.random.randint(0,10,10)
a8.sort()
print(a8)

for i,v in enumerate(a8):
   print("index of {} : {}".format(v,i))

[1 1 3 3 4 4 7 9 9 9]
index of 1 : 0
index of 1 : 1
index of 3 : 2
index of 3 : 3
index of 4 : 4
index of 4 : 5
index of 7 : 6
index of 9 : 7
index of 9 : 8
index of 9 : 9


19- 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [109]:
v2= np.random.randint(0,30,20)
print(v2)
getir=[2,4,6]
print(v2[getir])

[ 7 15 20 10 22 28 19 27  3 29 25 29  9 12 29 25 23 12 14  0]
[20 22 19]


20- 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [112]:
v3= np.random.randint(0,30,10)
print(v3)
v3[3]=16
print(v3)

[ 0  4 24  9  4 29  9 17 20  0]
[ 0  4 24 16  4 29  9 17 20  0]


21- “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

"""Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise köşegen matris denir. Köşegen_(Diagonal)_Matris_001 matrisi 3×3 türünde köşegen matristir."""

"""BİR MATRİSİN İZİ(TRACE)

Bir kare matrisinin kosegen elemanlarınin toplamına da A nın izi denir."""


22- 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [133]:
d= np.eye(5)
print(d)
print("################")
for i in range(len(d)):
    print("m[{},{}] is {}".format(i,i,d[i,i]))
        

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
################
m[0,0] is 1.0
m[1,1] is 1.0
m[2,2] is 1.0
m[3,3] is 1.0
m[4,4] is 1.0


23- 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [139]:
v4= np.arange(10,20)
print(v4)
print(v4[2:-1])

[10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18]


24- 10X10 luk bir matris olusturunuz ve ;
satir ve 5.sutuna ulasiniz.

sutunun tum satirlarina ulasiniz.

Tum sutunlarin 2.satirlarina ulasiniz.

tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.

satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.

satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.

sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.

indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [28]:
m1= np.random.randint(100, size = (10, 10))
print(m1)
print('    ########################')

print(m1[2,4]) # 3. satir ve 5.sutuna ulasiniz.
print('    ########################')
print(m1[:,4]) # sutunun tum satirlarina ulasiniz.
print('    ########################')
print(m1[1,:]) # Tum sutunlarin 2.satirlarina ulasiniz.
print('    ########################')
print(m1[2:6,:]) # Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
print('    ########################')
print(m1[2:5,3:7]) # Satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
print('    ########################')
print(m1[5:,:4]) # Satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
print('    ########################')
print(m1[:,(3,6,9)]) # Sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
print('    ########################')
print(m1[5,5]) # 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
m1[1,5]=1985
print('    ########################')
print(m1[1,5])


[[44 21 42 77 25 37 63 59 33 72]
 [57 64 68 90  2 54 49 71 80 95]
 [12 82 93 94 16 80 21 99 57 13]
 [96 77 42 94 21 81 58 95 16  8]
 [77  3 45 58 25 90 22 47 88 26]
 [81 28 87 28 38 68 78 75 34 64]
 [26 42 32 52 17 89  2 14 70 29]
 [95 82 89 33 85 58 23 65 16  5]
 [49 41  7 58 81 75 19 92 57 12]
 [94 15 21 51 26 10 30 75 43 28]]
    ########################
16
    ########################
[25  2 16 21 25 38 17 85 81 26]
    ########################
[57 64 68 90  2 54 49 71 80 95]
    ########################
[[12 82 93 94 16 80 21 99 57 13]
 [96 77 42 94 21 81 58 95 16  8]
 [77  3 45 58 25 90 22 47 88 26]
 [81 28 87 28 38 68 78 75 34 64]]
    ########################
[[94 16 80 21]
 [94 21 81 58]
 [58 25 90 22]]
    ########################
[[81 28 87 28]
 [26 42 32 52]
 [95 82 89 33]
 [49 41  7 58]
 [94 15 21 51]]
    ########################
[[77 63 72]
 [90 49 95]
 [94 21 13]
 [94 58  8]
 [58 22 26]
 [28 78 64]
 [52  2 29]
 [33 23  5]
 [58 19 12]
 [51 30 28]]
    ###################

25- 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

20 den buyuk olan kac deger var.

30’dan kucuk kac deger var

icerisinde 33 gecen kac deger var

olusturulan arrayin tum elemanlarini 5 ile carpin.

olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

olustural arrayin icerisinde, sadece sutunlara bakarak her bir sutunu toplayin ve toplami 30 dan buyuk kac sutun var

olustural arrayin icerisinde, sadece satirlara bakarak her bir satiri toplayin ve toplami 30 dan buyuk kac satir var.

In [29]:
arr1=np.arange(0,50,5)
print(arr1)
print("   ************************")
print(np.sum(arr1 > 20)) # 20 den buyuk olan kac deger var.

print("   ************************")
print(np.sum(arr1 < 30)) # 30’dan kucuk kac deger var.

print("   ************************")
print(np.sum(arr1 == 33)) # icerisinde 33 gecen kac deger var.

print("   ************************")
print(arr1 * 5) # olusturulan arrayin tum elemanlarini 5 ile carpin.

print("   ************************")
print(arr1 % 2) # olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

[ 0  5 10 15 20 25 30 35 40 45]
   ************************
5
   ************************
6
   ************************
0
   ************************
[  0  25  50  75 100 125 150 175 200 225]
   ************************
[0 1 0 1 0 1 0 1 0 1]


26- 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;

orlamasini aliniz.

standart sapmasini aliniz.

varyansini aliniz.

median’ini aliniz.

en kucuk degeri bulunuz.

en buyuk degeri bulunuz.

In [41]:
ar2 = np.linspace(0,1,50)
print(ar2)

print("  ---------------------------")
print("Mean: {}".format(np.mean(ar2)))

print("  ---------------------------")
print("Std: {}".format(np.std(ar2)))

print("  ---------------------------")
print("Var: {}".format(np.var(ar2)))

print("  ---------------------------")
print("Median: {}".format(np.median(ar2)))

print("  ---------------------------")
print("Max: {}".format(np.max(ar2)))

print("  ---------------------------")
print("Min: {}".format(np.min(ar2)))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
  ---------------------------
Mean: 0.5
  ---------------------------
Std: 0.2945075446869757
  ---------------------------
Var: 0.086734693877551
  ---------------------------
Median: 0.5
  ---------------------------
Max: 1.0
  ---------------------------
Min: 0.0


27- Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

In [42]:
"""
# Pandas seriler, numpy array ler gibi homojen olmak zorunda degil. 
Farkli data turlerini de bir serinin icinde gorebiliyor ve isleyebiliyoruz.

# Pandas seriler tek boyutlu, fakat numpy arrayleri cok boyutlu da olabiliyorlar.

# Pandas series yapisinda her bir verinin, sozluk yapisina benzer sekilde label ya da index gibi bir elemani var
"""

'\n# Pandas seriler, numpy array ler gibi homojen olmak zorunda degil. \nFarkli data turlerini de bir serinin icinde gorebiliyor ve isleyebiliyoruz.\n\n# Pandas seriler tek boyutlu, fakat numpy arrayleri cok boyutlu da olabiliyorlar.\n\n# Pandas series yapisinda her bir verinin, sozluk yapisina benzer sekilde label ya da index gibi bir elemani var\n'

28- Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [43]:
import pandas as pd

seri1 = pd.Series(["Ali",1,0.5,None," "], index = ('A','B','C','D','E'))
print(seri1)


A     Ali
B       1
C     0.5
D    None
E        
dtype: object


29- Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [46]:
dict1 = {"Hollanda":'Amsterdam', "Fransa":'Paris', "Italya":'Roma', "Yunanistan":'Atina', "Cin":'Pekin'}

seri2 = pd.Series(dict1)  #sozlugu seriye cevirdik
print(seri2)

Hollanda      Amsterdam
Fransa            Paris
Italya             Roma
Yunanistan        Atina
Cin               Pekin
dtype: object


30- 10 elemanli random bir vektor olusturun.

Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)

Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)

Serinin index sirasina gore 1. Elamanina ulasin.

Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)

Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)

Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

2 adet 5 elemanli seri olusturun.

Olusturdugunuz serileri birlestirin.

Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.

Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [67]:
v11=np.random.randint(0,20,10)
print(v11)
print("   ---------------------")

seri3 = pd.Series(v11, index = ('A','B','C','D','E','F','G','H','I','J'))
print(seri3)
print("   ---------------------")

print(seri3["C"])
print("   ---------------------")

print(seri3[1])
print("   ---------------------")

print(seri3[["B","G"]])
print("   ---------------------")

print(seri3["B":"G"])
print("   ---------------------")

print(seri3["D"::])
print("   ---------------------")

seri4 = pd.Series([1,2,3,4,5]) # 2 adet 5 elemanli seri olusturun.
seri5 = pd.Series([6,7,8,9,10])

seri6 = pd.concat([seri4, seri5]) 
print(seri6)
print("   ---------------------")

seri7 = pd.concat([seri4, seri5], ignore_index=True) 
print(seri7)
print("   ---------------------")

print(seri7.loc['4':'6'])
print("   ---------------------")
print(seri7.iloc[4:6])


[ 4 19  2 18 17 13  8  6  0  2]
   ---------------------
A     4
B    19
C     2
D    18
E    17
F    13
G     8
H     6
I     0
J     2
dtype: int32
   ---------------------
2
   ---------------------
19
   ---------------------
B    19
G     8
dtype: int32
   ---------------------
B    19
C     2
D    18
E    17
F    13
G     8
dtype: int32
   ---------------------
D    18
E    17
F    13
G     8
H     6
I     0
J     2
dtype: int32
   ---------------------
0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64
   ---------------------
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
   ---------------------
4    5
5    6
6    7
dtype: int64
   ---------------------
4    5
5    6
dtype: int64


# Master odev ;
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [100]:
import time
n=0
t1=time.time()

while True:
    n+=1
    m1 = np.random.rand(20,20)
    m2 = np.random.rand(20,20)
    d = np.diag(m1-m2)
    ok = True
    for v in d:
        if v > 0.1 or v < -0.1:
            ok = False
            break
    if ok:
        print(d)
        break


t2=time.time()
duration = t2-t1
print(duration, n)

[-0.05318667 -0.07569373  0.0237268  -0.05002649]
0.0060002803802490234 280
