In [1]:
# 1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
# Vektor --> Tek boyutli dizi
# Matris --> 2 boyutlu dizi

In [2]:
# 2.	10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np
liste = [0,1,2,3,4,5,6,7,8,9]
np.array(liste)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10),dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
# 4 	Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10),dtype= float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10),9,dtype= int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
# 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# 7.	-1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace(-1, 1, 30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [8]:
# 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
# 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
np.eye(10)  
#  np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# 10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
# •	eleman sayisini
# •	boyut bilgisini/sayisini
# •	satir X sutun bilgisini
# •	veri tipini numpy metodlariyla yazdiriniz.

data = np.random.randint(10, size=(5,10))
print(data)
print('eleman sayisi:',data.size)   # eleman sayisi
print('boyut bilgisi:',data.ndim)   # boyut bilgisi
print('satir sutun bilgisi:',data.shape)  # satir sutun bilgisi
print('veri tipi:',data.dtype)  # veri tipi




[[4 3 7 4 4 0 6 0 0 2]
 [6 4 1 7 7 5 8 2 9 7]
 [9 5 7 1 7 9 9 9 8 1]
 [6 3 6 9 8 6 0 9 8 9]
 [1 3 8 3 5 8 5 7 3 0]]
eleman sayisi: 50
boyut bilgisi: 2
satir sutun bilgisi: (5, 10)
veri tipi: int32


In [11]:
# 11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu)
np.random.randint(10, size=(3,4,7))


array([[[0, 7, 4, 1, 7, 5, 1],
        [1, 6, 4, 6, 2, 8, 8],
        [9, 0, 8, 4, 9, 0, 4],
        [9, 6, 7, 5, 8, 1, 1]],

       [[2, 2, 2, 7, 1, 7, 2],
        [7, 0, 7, 8, 6, 9, 3],
        [0, 8, 7, 3, 4, 2, 8],
        [5, 4, 0, 5, 4, 1, 6]],

       [[1, 6, 1, 5, 9, 0, 4],
        [6, 7, 9, 8, 7, 2, 3],
        [5, 4, 2, 9, 8, 4, 0],
        [5, 7, 5, 7, 4, 9, 3]]])

In [12]:
# 12.	Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# 13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
a = np.arange(1,5)
b = np.arange(11,15)
c = np.arange(111,115)
d = np.arange(1111,1115)
np.concatenate([a,b,c,d])




array([   1,    2,    3,    4,   11,   12,   13,   14,  111,  112,  113,
        114, 1111, 1112, 1113, 1114])

In [14]:
# 14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

x = np.array([[11], [22]])

y = np.array([[3, 4, 5], [6, 7, 8]])
np.hstack([x,y])

array([[11,  3,  4,  5],
       [22,  6,  7,  8]])

In [15]:
# 15.	Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

# axis=0  satiri, x eksenini, yatayi
# axis=1  sutunu, y eksenini, dikeyi   temsil  eder.

In [16]:
# 16.	Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
a = np.arange(6)                # 1x6 boyutunda arrayi 3x3 array ile birlestirmek istiyoruz
a = np.arange(6).reshape(2,3)   # 1x6 arrayi 2x3'e cevirebiliriz
b = np.array([[7,7,7],[8,8,8],[9,9,9]])    # bu durumda 3x3 ile dikey olarak birlestirebiliriz       
np.vstack((a, b))      # ayni boyuta getirip birlestirebiliriz

array([[0, 1, 2],
       [3, 4, 5],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

In [17]:
x = np.array([1,2,3])                   # 1x3 ile
y = np.arange(9).reshape(3,3)           # 3x3 yatay olarak birlestirmek icin
z = np.hstack((x, y.reshape(9,)))       # ayni boyuta getirip (3x3 = 1x9) birlestirebiliriz
print("\n",z)


 [1 2 3 0 1 2 3 4 5 6 7 8]


In [18]:
# 17.	10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.
dizi = [1,2,3,4,5,6,7,8,9,10]
a,b,c,d,e = np.split(dizi, [2,4,6,8])
a,b,c,d,e

(array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]))

In [19]:
# 18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [20]:
data = np.random.randint(10, size=10)
data.sort()
data

array([0, 0, 0, 4, 5, 6, 6, 6, 9, 9])

In [21]:
# 19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
data = np.random.randint(10, size=20)
print(data)
sec=[3,5,7]
print(data[sec])

[5 9 7 8 0 3 5 0 9 2 4 8 3 1 4 4 9 4 1 0]
[8 3 0]


In [22]:
# 20.	10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
data = np.random.randint(10, size=10)
print(data)
data[4]=99
print(data)


[4 8 3 5 3 5 3 5 7 5]
[ 4  8  3  5 99  5  3  5  7  5]


21.	“Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise köşegen yani "DIAGONAL matris" matris denir.

Kosegen uzerindeki elemanlarin toplamina Matris izi "Trace of Matrix" denir



In [23]:
# 22.	5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
dizi = np.eye(5,5)
print(dizi)

print(dizi[[0,1,2,3,4],[0,1,2,3,4]])    # dizi ile

for i in range (len(dizi)):             # dongu ile
    print(dizi[i,i])


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]
1.0
1.0
1.0
1.0
1.0


In [24]:
# 23.	10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
dizi = np.arange(10,20)
dizi[3:]


array([13, 14, 15, 16, 17, 18, 19])

In [25]:
# 24.	10X10 luk bir matris olusturunuz ve ;
# •	3.satir ve 5.sutuna ulasiniz.
# •	5.sutunun tum satirlarina ulasiniz.
# •	Tum sutunlarin 2.satirlarina ulasiniz.
# •	tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
# •	satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
# •	satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
# •	sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
# •	5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

data = np.arange(100).reshape(10,10)
print(data)
print(data[3,5])
print()
print(data[:,5])
print()
print(data[2,:])
print()
print(data[2:7,:])
print()
print(data[2:5,3:7])
print()
print(data[5:,:4])
print()
print(data[:,[3,6,9]])
print()
data[5,5]=1971
print(data)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
35

[ 5 15 25 35 45 55 65 75 85 95]

[20 21 22 23 24 25 26 27 28 29]

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]

[[23 24 25 26]
 [33 34 35 36]
 [43 44 45 46]]

[[50 51 52 53]
 [60 61 62 63]
 [70 71 72 73]
 [80 81 82 83]
 [90 91 92 93]]

[[ 3  6  9]
 [13 16 19]
 [23 26 29]
 [33 36 39]
 [43 46 49]
 [53 56 59]
 [63 66 69]
 [73 76 79]
 [83 86 89]
 [93 96 99]]

[[   0    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33   34 

In [26]:
# 25.	0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
# •	20 den buyuk olan kac deger var.
# •	30’dan kucuk kac deger var
# •	icerisinde 33 gecen kac deger var
# •	olusturulan arrayin tum elemanlarini 5 ile carpin.
# •	olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.


In [27]:
data = np.arange(0,50,5)
print(data)
print(np.sum(data > 20))
print(np.sum(data < 30)) 
print(np.sum(data == 33)) 
print(data * 5)
print(data % 2) 


[ 0  5 10 15 20 25 30 35 40 45]
5
6
0
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [28]:
# 26.	0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
# •	ortalamasini aliniz.
# •	standart sapmasini aliniz.
# •	varyansini aliniz.
# •	median’ini aliniz.
# •	en kucuk degeri bulunuz.
# •	en buyuk degeri bulunuz.

data1=np.random.rand(1,50)
print(data1.mean())
print(data1.std())
print(data1.var())
print(np.median(data1))
print(np.min(data1))
print(np.max(data1))



0.5208355526867622
0.28238527955329407
0.07974144610839204
0.5584862056665023
0.040928318256456375
0.9952518006379161


In [29]:
#27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.
# 1) Pandas serileri farkli veri tipleri barindirabilir
# 2) Indexlerde degisiklik yapma imkani vardir

In [30]:
# 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.
import pandas as pd
seri = pd.Series([1, 2.3 , None, "ali", True], index = ('A','B','C','D','E'))
seri

A       1
B     2.3
C    None
D     ali
E    True
dtype: object

In [31]:
# 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

sozluk = { "Hollanda" : "Amsterdam", "Cin" : "Pekin", "Italya" : "Roma","Japonya" : "Tokyo", "Malta" : "Valetta"}
new_seri = pd.Series(sozluk)
new_seri

Hollanda    Amsterdam
Cin             Pekin
Italya           Roma
Japonya         Tokyo
Malta         Valetta
dtype: object

In [32]:
# 30.	
# a) 10 elemanli random bir vektor olusturun.
# b) Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
# c) Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
# d) Serinin index sirasina gore 1. Elamanina ulasin.
# e) Index ismine gore serinin 2. Ve 7. Eleman. ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
# f) Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
# g) Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

data = np.random.randint(10, size=10)   # a
new_seri = pd.Series(data,  index = ('A','B','C','D','E', 'F', 'G', 'H', 'I', 'J')) # b
print(new_seri)
print(new_seri['C'])        # c   
print(new_seri[0])          # d
print(new_seri[['B','G']])  # e
print(new_seri['B':'G'])    # f
print(new_seri[4:])         # g

A    0
B    7
C    4
D    3
E    4
F    7
G    2
H    7
I    9
J    8
dtype: int32
4
0
B    7
G    2
dtype: int32
B    7
C    4
D    3
E    4
F    7
G    2
dtype: int32
E    4
F    7
G    2
H    7
I    9
J    8
dtype: int32


In [39]:
# 31.	
# a) 2 adet 5 elemanli seri olusturun.
# b) Olusturdugunuz serileri birlestirin.
# c) Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
# d) Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

liste1=pd.Series([1,2,3,4,5])
liste2=pd.Series([11,22,33,44,55])
list_con = pd.concat([liste1, liste2])  
list_con.index=range(1,11)
print(list_con)

print(list_con.loc['4':'6'])
print(list_con.iloc[3:6])

1      1
2      2
3      3
4      4
5      5
6     11
7     22
8     33
9     44
10    55
dtype: int64
4     4
5     5
6    11
dtype: int64
4     4
5     5
6    11
dtype: int64


In [ ]:
# Master odev ;
# Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.


In [40]:
import numpy as np
import time

loop_count = 0
start_time = time.time()

while True:
    loop_count += 1

    matrix1 = np.random.rand(5, 5)
    matrix2 = np.random.rand(5, 5)

    dif_matrix = matrix1 - matrix2
    samp_matr = np.diag(dif_matrix)

    if len(list(filter(lambda x: x > 0.1 or x < -0.1, samp_matr))) == 0:
        break

end_time = time.time()
time_diff = end_time - start_time

print("Gecen Zaman : ", time_diff, "saniye")
print("Dongu Sayisi: ", loop_count, "kez")
print("Matris: ", samp_matr)


# Gecen Zaman :  0.26086950302124023 saniye
# Dongu Sayisi:  2151 kez
# Matris:  [-0.08305188 -0.00240248 -0.07821575  0.07195702  0.0877937 ]

# 10x10 Matris icin sonuclar
# Gecen Zaman :  1324.5193932056427 saniye
# Dongu Sayisi:  25308910 kez
# Matris:  [-0.01020434 -0.02920587 -0.06702373  0.08481768  0.08566514 -0.00427998
#  -0.05745753 -0.09594201 -0.02223689  0.08269153]

Gecen Zaman :  0.26086950302124023 saniye
Dongu Sayisi:  2151 kez
Matris:  [-0.08305188 -0.00240248 -0.07821575  0.07195702  0.0877937 ]
