In [245]:
import numpy as np 
import pandas as pd

1- Tek indeksli diziler vektörler, iki ya da daha fazla indeksli diziler ise matrsiler ya da tablolar olarak adlandırılırlar.

In [3]:
# 2.sorunun cevabi
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#3.sorunun cevabi
np.zeros((10,10), dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
#4.sorunun cevabi

np.ones((10,10),dtype = 'float32') 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [13]:
#5.sorunun cevabi

np.full((10,10),9)



array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [61]:
#6.sorunun cevabi

np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [15]:
#7.sorunun cevabi

np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [16]:
#8.sorunun cevabi

np.random.randint(0,30, (5,6)) 

array([[10,  3, 24, 17, 21,  1],
       [ 9,  7, 18, 28,  2, 10],
       [11,  1, 22, 25, 18, 13],
       [ 5, 22, 29, 14, 18, 24],
       [29,  6, 22, 23, 14, 13]])

In [21]:
# 9.sorunun cevabi

np.eye(10,dtype="int") 

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [341]:
#10.sorunun cevabi

a=np.random.randint(0,10, (5,10)) 

print("a=",a,sep='\n')


print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape)
print("Toplam eleman sayisi =  ",a.size)
print("Veri tipi =  ",a.dtype)

a=
[[8 1 4 6 3 8 8 0 1 1]
 [6 8 8 4 0 6 7 9 2 7]
 [7 6 6 6 4 4 8 0 1 1]
 [9 9 1 6 4 2 4 1 5 9]
 [8 2 9 8 2 4 3 1 8 9]]
Boyut sayisi =   2
satir, sutun bilgisi =   (5, 10)
Toplam eleman sayisi =   50
Veri tipi =   int32


In [30]:
#11. sorunun cevabi

a = np.random.randint(10, size = (3,4,7))
a

array([[[7, 9, 0, 6, 9, 4, 0],
        [0, 7, 4, 1, 7, 7, 8],
        [7, 6, 9, 6, 2, 7, 6],
        [4, 9, 5, 5, 3, 9, 7]],

       [[3, 5, 5, 5, 8, 2, 0],
        [1, 5, 5, 1, 2, 9, 7],
        [0, 2, 9, 2, 4, 7, 7],
        [0, 3, 5, 4, 0, 9, 4]],

       [[1, 5, 7, 4, 6, 2, 1],
        [6, 1, 2, 7, 1, 6, 1],
        [5, 0, 5, 6, 0, 2, 7],
        [8, 7, 8, 4, 3, 9, 0]]])

In [340]:
#12.sorunun cevabi

a = np.array([1,2,3,5,6,7,8,9,0]) 
print("Vektor olusturduk=",a)
print("a boyut=",a.ndim)

b = a.reshape((3,3))
print("3x3 luk 2 boyutlu matrise cevirdik="  ,b,sep='\n')
print("b boyut=",b.ndim)

Vektor olusturduk= [1 2 3 5 6 7 8 9 0]
a boyut= 1
3x3 luk 2 boyutlu matrise cevirdik=
[[1 2 3]
 [5 6 7]
 [8 9 0]]
b boyut= 2


In [92]:
#13. sorunun cevabi

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c=np.array([7, 8, 9])

d=np.array([10, 11, 12])
print("a=",a)
print("b=",b)
print("c=",c)
print("d=",d)

birlestirme=np.concatenate([a,b,c,d])
print("birlestirme=",birlestirme)

a= [1 2 3]
b= [4 5 6]
c= [7 8 9]
d= [10 11 12]
birlestirme= [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [339]:
# 14.sorunun cevabi

a = np.array([[99],
              [99]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
print("a=",a)
print("b=",b)
birlestirme=np.hstack([a,b])
print("birlestirme=",birlestirme,sep='\n')

a= [[99]
 [99]]
b= [[9 8 7]
 [6 5 4]]
birlestirme=


[[99  9  8  7]
 [99  6  5  4]]


15.sorunun cevabi = Numpy’da boyutlar axis olarak isimlendirilir,axis hangi bazda işlem 
yapacağınızı açıklar, eğer axis 0 olursa satır bazında axis 1 olursa sütun bazında işlem
yapacağınız anlamına gelir.


In [338]:
#16. sorunun cevabi 

a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])
print("a=",a)
print("b=",b)
birlestirme=np.vstack([a,b])
print("birlestirme=",birlestirme,sep='\n')

a= [1 2 3]
b= [[9 8 7]
 [6 5 4]]
birlestirme=
[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [102]:
# 17. sorunun cevabi

x = [1, 2, 3, 4,5,6,7,8,9,10]
print("x",x)
bolme_split=np.split(x, [3,6,9])

print("4 parca bolme islemi=",bolme_split)

x [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4 parca bolme islemi= [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]


4 parca bolme islemi= [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]


In [127]:
# 18.sorunun cevabi

array_random=np.random.randint(10, size = 10)
array_random



array([3, 9, 7, 5, 4, 6, 2, 4, 2, 0])

In [128]:
np.sort(array_random) # siralama yapildi

array([0, 2, 2, 3, 4, 4, 5, 6, 7, 9])

In [129]:
np.argsort(array_random) # siralamadan sonra her elelmanin ilk arary daki yerini tespit ettik ornegin 0 elemani arrayda 9.sirada

array([9, 6, 8, 0, 4, 7, 3, 5, 2, 1], dtype=int64)

In [151]:
# 19.sorunun cevabi

a = np.random.randint(10, size = 20)

print("a=",a)

eleman_3=a[3]
eleman_5=a[5]
eleman_7=a[7]
print(eleman_3)
print(eleman_5)
print(eleman_7)

a= [6 3 0 4 5 4 2 2 4 9 5 9 7 6 3 1 1 9 9 2]
4
4
2


In [157]:
#20. sorunun cevabi

a = np.random.randint(10, size = 10)
print("a=",a)
eleman_4_degisim=a[3] = 1
print("eleman_4_degisim=",eleman_4_degisim)
print(print("a=",a))


a= [4 5 2 7 4 9 1 4 1 9]
eleman_4_degisim= 1
a= [4 5 2 1 4 9 1 4 1 9]
None


#21.sorunun cevabi

Diagonal Matrix, köşegen dışı tüm girişlerin sıfır olduğu bir matristir. 
Trace Matrix,Bir kare matrisin ana köşegenindeki elemanların toplamı. 


In [337]:
#22.sorunun cevabi

a=np.random.randint(0,30, (5,5)) #oncelikle bir matrix olusturduk
print('a_matrix=',a,sep='\n')

print("diagonal_matrix",a.diagonal())




a_matrix=
[[ 7 15  9 17 24]
 [ 8 14 22  1 15]
 [ 9 24 19 16 29]
 [10  0 14  4 22]
 [11  2  0 26 20]]
diagonal_matrix [ 7 14 19  4 20]


In [166]:
#23. sorunun cevabi

a = np.arange(10,20)
print("a=",a)
print("3.indexten Sonraki Degerler=",a[3:] )

a= [10 11 12 13 14 15 16 17 18 19]
3.indexten Sonraki Degerler= [13 14 15 16 17 18 19]


In [331]:
#24.sorunun cevabi

a = np.random.randint(10, size = (10, 10))
print("a....=",a,sep='\n')

print("----------------------------3.Satirin 5.Sutunu.....=",a[3:,5])
print("----------------------------5.Sutunun Tum Satirlarina.....=",a[:,5])
print("----------------------------Tum Sutunlarin 2.Satiri=",a[2,:])
print("-------------Tum Sutunlarin 2 ile 7 arasi Satirlari=",a[2:7,:],sep='\n')
print("--------------------Satir 2 den 5 e-sutun 3 den 7 e=",a[2:5,3:7],sep='\n')
print("-----------------Satir 5 den sona e-sutun 0 dan 4 e=",a[5:,:4],sep='\n')
print("------------------------3-6-9 sutunlarin tum satiri=",a[0:,[3,6,9]],sep='\n')
a[5,5]=1978
print("---------------------5inci sutun-5.satir degistirme=",a,sep='\n')

a....=
[[9 1 8 4 5 3 2 7 1 2]
 [3 0 3 1 4 2 0 6 7 3]
 [7 1 3 4 8 5 0 5 0 5]
 [4 1 7 4 9 4 3 7 8 9]
 [4 0 1 3 1 9 4 4 0 7]
 [8 0 3 8 3 9 8 1 8 8]
 [9 6 9 9 0 5 8 0 6 1]
 [4 0 9 8 9 5 6 7 3 2]
 [7 2 1 4 6 4 1 0 4 7]
 [0 8 9 5 1 9 2 3 0 9]]
----------------------------3.Satirin 5.Sutunu.....= [4 9 9 5 5 4 9]
----------------------------5.Sutunun Tum Satirlarina.....= [3 2 5 4 9 9 5 5 4 9]
----------------------------Tum Sutunlarin 2.Satiri= [7 1 3 4 8 5 0 5 0 5]
-------------Tum Sutunlarin 2 ile 7 arasi Satirlari=
[[7 1 3 4 8 5 0 5 0 5]
 [4 1 7 4 9 4 3 7 8 9]
 [4 0 1 3 1 9 4 4 0 7]
 [8 0 3 8 3 9 8 1 8 8]
 [9 6 9 9 0 5 8 0 6 1]]
--------------------Satir 2 den 5 e-sutun 3 den 7 e=
[[4 8 5 0]
 [4 9 4 3]
 [3 1 9 4]]
-----------------Satir 5 den sona e-sutun 0 dan 4 e=
[[8 0 3 8]
 [9 6 9 9]
 [4 0 9 8]
 [7 2 1 4]
 [0 8 9 5]]
------------------------3-6-9 sutunlarin tum satiri=
[[4 2 2]
 [1 0 3]
 [4 0 5]
 [4 3 9]
 [3 4 7]
 [8 8 8]
 [9 8 1]
 [8 6 2]
 [4 1 7]
 [5 2 9]]
---------------------5inci 

In [235]:
#25.sorunun cevabi

a=np.arange(0,50,5)
print("a............=",a)
print("20 den Buyuk Degerler=",np.sum(a > 20) )
print("30 dan Kucuk Degerler=",np.sum(a < 30) )
print("33 Olan Degerler=",np.sum((a > 33) & (a < 33)))
print("Tum Elemanlarin 5 ile Carpimi=",a * 5)
print("Tum Elemanlarin 2 ile Bolumunden Kalan=",a % 2)


a............= [ 0  5 10 15 20 25 30 35 40 45]
20 den Buyuk Degerler= 5
30 dan Kucuk Degerler= 6
33 Olan Degerler= 0
Tum Elemanlarin 5 ile Carpimi= [  0  25  50  75 100 125 150 175 200 225]
Tum Elemanlarin 2 ile Bolumunden Kalan= [0 1 0 1 0 1 0 1 0 1]


In [321]:
#26.sorunun cevabi
a=np.linspace(0,1,50)
print("a........=",a,sep='\n\n')
print("Ortalamasi...........=",np.mean(a))
print("Standart Sapma.......=",np.std(a))
print("Varyans..............=",np.var(a))
print("Median...............=",np.median(a))
print("En Kucuk Deger.......=",np.min(a))
print("En Buyuk Deger.......=",np.max(a))


a........=

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
Ortalamasi...........= 0.5
Standart Sapma.......= 0.2945075446869757
Varyans..............= 0.086734693877551
Median...............= 0.5
En Kucuk Deger.......= 0.0
En Buyuk Deger.......= 1.0


In [248]:
#28.Sorunun Cevabi

seri2 = pd.Series(["Ahmet","Mehmet",3, 4.6, " --- "]) 
seri2

0     Ahmet
1    Mehmet
2         3
3       4.6
4      --- 
dtype: object

In [320]:
#  29.sorunun cevabi
sozluk = { "Fransa" : "Paris", "Italya" : "Roma", "Portekiz" : "Lizbon", "Almanya":"Berlin","Mozambik":"Maputo"} 
print("sozluk....=",sozluk)
print("Sozluk Seriye Donusturme......=",pd.Series(sozluk),sep='\n')

sozluk....= {'Fransa': 'Paris', 'Italya': 'Roma', 'Portekiz': 'Lizbon', 'Almanya': 'Berlin', 'Mozambik': 'Maputo'}
Sozluk Seriye Donusturme......=
Fransa       Paris
Italya        Roma
Portekiz    Lizbon
Almanya     Berlin
Mozambik    Maputo
dtype: object


In [318]:
#30. sorunun cevabi

a = np.random.randint(10, size =10)
print("a............=",a)
z=pd.Series((a), index = ('a','b','c','d','e','f','g','h','i','j'))
print(z)
print('Serinin 3.Elemani..................................=',z["c"] )
print('Serinin 1.Elemani..................................=',z["a"] )
print('Serinin 2. ve 7.Elemani............................=',z["b"],z['g'] )
print('Serinin 2 ve 7.Elemanlari arasi....................=',z["b":"g"],sep='\n\n\n' )
print('Serinin 4 den itibaren tum Elemanlari..............=',z["b":],sep='\n\n\n' )


a............= [0 5 4 4 9 2 6 6 9 0]
a    0
b    5
c    4
d    4
e    9
f    2
g    6
h    6
i    9
j    0
dtype: int32
Serinin 3.Elemani..................................= 4
Serinin 1.Elemani..................................= 0
Serinin 2. ve 7.Elemani............................= 5 6
Serinin 2 ve 7.Elemanlari arasi....................=


b    5
c    4
d    4
e    9
f    2
g    6
dtype: int32
Serinin 4 den itibaren tum Elemanlari..............=


b    5
c    4
d    4
e    9
f    2
g    6
h    6
i    9
j    0
dtype: int32


In [357]:
# 31.sorunun cevabi

seri1 = pd.Series([1,2,3,4,5])  
print('Seri1.....=',seri1,sep='\n')
seri2 = pd.Series(['a','b','c','d','e'])
print('Seri2.....=',seri2,sep='\n')
seri = pd.concat([seri1, seri2], ignore_index=True)
print('Seri.....=',seri,sep='\n')
print('Seridekiindexi 4,5,6 Olan Degerserler.....=',seri.iloc[4:7],sep='\n')

Seri1.....=
0    1
1    2
2    3
3    4
4    5
dtype: int64
Seri2.....=
0    a
1    b
2    c
3    d
4    e
dtype: object
Seri.....=
0    1
1    2
2    3
3    4
4    5
5    a
6    b
7    c
8    d
9    e
dtype: object
Seridekiindexi 4,5,6 Olan Degerserler.....=
4    5
5    a
6    b
dtype: object


Master odev ;

In [ ]:
import random
import numpy as np
import pandas as pn


m1=[[0 for x in range(20) ]for y in range(20)]
m2=[[0 for x in range(20) ]for y in range(20)]


for i in range(20):
    for j in range(20):
        m1[i][j]= random.randint(0,9)
        m2[i][j] = random.randint(0,9)

cikarma=np.subtract(m1,m2)
print('Matrix_1.....=',m1)
print('Matrix_2.....=',m2)
print('Sonuc M1-M2....=',cikarma,sep='\n')
print("diagonal_matrix....=",cikarma.diagonal())