# Class4-Data_Analysis-Week17

---------------------------------

# Numpy ve Pandas ile ilgili Odev
1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.


In [1]:
import numpy as np
import pandas as pd

Vector has only one dimension, But matrix, on the other hand, has multiple dimension.

2.	10 elemanli bir listeden NumPy Array’i olusturunuz.


In [2]:
list_with_ten = [1,2,3,4,5,6,7,8,9,10]
array_from_list = np.array(list_with_ten)
print(array_from_list)

[ 1  2  3  4  5  6  7  8  9 10]


3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.


In [3]:
ten_by_ten=np.zeros((10,10), dtype='int')
ten_by_ten

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4.	Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.


In [4]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.


In [5]:
np.full((10,10), 9, dtype='int')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.


In [6]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

7.	-1 ile 1 arasinda 30 adet Array olusturunuz.


In [7]:
np.linspace(-1,1, 30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.


In [8]:
np.arange(0,30).reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 


In [9]:
np.eye(10, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
  * eleman sayisini
  * boyut bilgisini/sayisini
  * satir X sutun bilgisini
  * veri tipini numpy metodlariyla yazdiriniz.


In [10]:
zero_ten = np.random.randint(10, size=(5,10))
zero_ten

array([[0, 0, 4, 0, 2, 9, 4, 1, 2, 2],
       [2, 6, 8, 3, 3, 4, 8, 5, 8, 6],
       [9, 7, 3, 7, 7, 7, 0, 3, 8, 6],
       [7, 3, 6, 2, 9, 3, 7, 1, 1, 2],
       [3, 5, 3, 1, 2, 8, 7, 9, 1, 1]])

In [11]:
zero_ten.size

50

In [12]:
zero_ten.ndim

2

In [13]:
zero_ten.shape

(5, 10)

In [14]:
zero_ten.dtype

dtype('int64')

11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 


In [15]:
a = np.random.randint(10, size=(3,4,7))
a

array([[[2, 3, 4, 2, 8, 6, 1],
        [2, 4, 0, 2, 8, 5, 4],
        [4, 2, 0, 9, 3, 1, 0],
        [3, 9, 1, 4, 4, 6, 8]],

       [[5, 1, 0, 7, 3, 3, 3],
        [3, 0, 1, 3, 9, 8, 8],
        [7, 0, 0, 3, 3, 2, 8],
        [5, 5, 3, 9, 5, 4, 1]],

       [[1, 3, 2, 1, 9, 8, 5],
        [3, 9, 4, 6, 7, 7, 8],
        [5, 6, 6, 5, 2, 1, 5],
        [6, 6, 9, 5, 1, 6, 3]]])

12.	Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)


In [16]:
b= np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.


In [18]:
aa = np.arange(6)
bb = np.arange(6)
cc = np.arange(6)
dd = np.arange(6)
ee = np.concatenate([aa,bb,cc,dd])

ee

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
       4, 5])

14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,


In [19]:
single_column = np.arange(2).reshape((2,1))
double_column = np.arange(10).reshape((2,5))
np.hstack([single_column,double_column])

array([[0, 0, 1, 2, 3, 4],
       [1, 5, 6, 7, 8, 9]])

15.	Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  


* axis=1 satir bazli toplama, axis=0 sutun bazli toplama yapar.

16.	Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.


In [20]:
c = np.random.normal(0, 1, (5,3))
c

array([[ 0.71963294,  1.69252216, -0.61229046],
       [ 1.09060317, -1.13508045, -0.48630108],
       [-0.53450444,  1.82436859, -0.86851116],
       [ 0.18315399, -0.04765785,  0.56983585],
       [ 0.44164164,  1.663347  ,  0.90504783]])

In [21]:
c.sum()

5.405807726971701

In [22]:
c.sum(axis=0)

array([ 1.9005273 ,  3.99749944, -0.49221901])

In [23]:
c.sum(axis=1)

array([ 1.79986463, -0.53077836,  0.42135299,  0.705332  ,  3.01003646])

17.	10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.


In [24]:
list_with_ten

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
e,f,g,h,i = np.split(list_with_ten, [2,4,6,8])
print(e,f,g,h,i)

[1 2] [3 4] [5 6] [7 8] [ 9 10]


18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.


In [26]:
random_array = np.random.randint(50, size =(15))
random_array_sorted = np.sort(random_array)
random_array_sorted

array([ 0,  0,  5, 10, 12, 14, 16, 24, 26, 27, 34, 36, 39, 45, 45])

In [27]:
for i in range(len(random_array_sorted)):
    print(f"{i}th element is {random_array_sorted[i]}")

0th element is 0
1th element is 0
2th element is 5
3th element is 10
4th element is 12
5th element is 14
6th element is 16
7th element is 24
8th element is 26
9th element is 27
10th element is 34
11th element is 36
12th element is 39
13th element is 45
14th element is 45


19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.


In [28]:
twenty_element = np.random.randint(20, size=20)
twenty_element[[3,5,7]]

array([15, 13,  5])

20.	10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.


In [29]:
kk = np.random.randint(20, size=10)
kk

array([ 2, 18, 11, 15, 19, 17, 13,  2,  9, 16])

In [30]:
kk[4] = 20
kk

array([ 2, 18, 11, 15, 20, 17, 13,  2,  9, 16])

21.	“Diagonal Matrix” ve “Trace of Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.


diagonal Matrix kosegeni disindaki tum verilerin 0 oldugu matrixtir. Kare veya dikdortgen olabilirler. see https://en.wikipedia.org/wiki/Diagonal_matrix

Trace of Matrix: Kosegen elementlerinin toplamidir.

22.	5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)


In [31]:
five_by_five = np.random.randint(0,20, size=(5,5))
for i in range(5):
    print(f"{i} x {i} element is {five_by_five[i,i]}")

0 x 0 element is 6
1 x 1 element is 10
2 x 2 element is 8
3 x 3 element is 9
4 x 4 element is 18


23.	10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.


In [32]:
array_deneme = np.arange(10, 20)
array_deneme[3:]

array([13, 14, 15, 16, 17, 18, 19])

24.	10X10 luk bir matris olusturunuz ve ;
* 3.satir ve 5.sutuna ulasiniz.
* 5.sutunun tum satirlarina ulasiniz.
* Tum sutunlarin 2.satirlarina ulasiniz.
* tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
* satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
* satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
* sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
* 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 


In [33]:
a = np.random.randint(20, size=(10,10))
a

array([[16, 18,  6, 19, 12,  8,  3,  2, 12, 18],
       [ 2, 11,  3,  4, 12,  3, 10,  5,  3, 10],
       [ 4,  3,  1,  7,  8, 18, 17,  0,  8, 16],
       [ 5,  0,  5, 18, 19,  4,  6, 11,  1,  9],
       [ 0,  5, 15, 11, 17, 15, 16,  9, 10, 16],
       [ 2, 13,  1,  0, 17,  4,  7, 15, 13, 19],
       [ 8, 15, 16,  9, 18,  6, 13, 14, 10, 17],
       [ 9,  0, 14, 10, 18,  7,  5, 18,  3,  8],
       [ 2, 11,  3,  8,  4,  9, 10, 17,  8,  2],
       [ 9, 17,  3, 13,  7,  6,  3, 12, 11, 13]])

In [34]:
a[2,4]

8

In [35]:
a[4,]

array([ 0,  5, 15, 11, 17, 15, 16,  9, 10, 16])

In [36]:
a[:,2]

array([ 6,  3,  1,  5, 15,  1, 16, 14,  3,  3])

In [37]:
a[:,1:7]

array([[18,  6, 19, 12,  8,  3],
       [11,  3,  4, 12,  3, 10],
       [ 3,  1,  7,  8, 18, 17],
       [ 0,  5, 18, 19,  4,  6],
       [ 5, 15, 11, 17, 15, 16],
       [13,  1,  0, 17,  4,  7],
       [15, 16,  9, 18,  6, 13],
       [ 0, 14, 10, 18,  7,  5],
       [11,  3,  8,  4,  9, 10],
       [17,  3, 13,  7,  6,  3]])

In [38]:
a[2:5,3:7]

array([[ 7,  8, 18, 17],
       [18, 19,  4,  6],
       [11, 17, 15, 16]])

In [39]:
a[5:,:4]

array([[ 2, 13,  1,  0],
       [ 8, 15, 16,  9],
       [ 9,  0, 14, 10],
       [ 2, 11,  3,  8],
       [ 9, 17,  3, 13]])

In [40]:
a[:,[3,6,9]]

array([[19,  3, 18],
       [ 4, 10, 10],
       [ 7, 17, 16],
       [18,  6,  9],
       [11, 16, 16],
       [ 0,  7, 19],
       [ 9, 13, 17],
       [10,  5,  8],
       [ 8, 10,  2],
       [13,  3, 13]])

In [41]:
a[5,5] = 1990

In [42]:
a

array([[  16,   18,    6,   19,   12,    8,    3,    2,   12,   18],
       [   2,   11,    3,    4,   12,    3,   10,    5,    3,   10],
       [   4,    3,    1,    7,    8,   18,   17,    0,    8,   16],
       [   5,    0,    5,   18,   19,    4,    6,   11,    1,    9],
       [   0,    5,   15,   11,   17,   15,   16,    9,   10,   16],
       [   2,   13,    1,    0,   17, 1990,    7,   15,   13,   19],
       [   8,   15,   16,    9,   18,    6,   13,   14,   10,   17],
       [   9,    0,   14,   10,   18,    7,    5,   18,    3,    8],
       [   2,   11,    3,    8,    4,    9,   10,   17,    8,    2],
       [   9,   17,    3,   13,    7,    6,    3,   12,   11,   13]])

25.	0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
* 20 den buyuk olan kac deger var.
* 30’dan kucuk kac deger var
* icerisinde 33 gecen kac deger var
* olusturulan arrayin tum elemanlarini 5 ile carpin.
* olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.



In [43]:
b = np.arange(0,50,5)
np.sum(b>20)

5

In [44]:
np.sum(b<30)

6

In [45]:
np.sum(b==33)

0

In [46]:
b*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [47]:
b%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

26.	0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
* orlamasini aliniz.
* standart sapmasini aliniz.
* varyansini aliniz.
* median’ini aliniz.
* en kucuk degeri bulunuz.
* en buyuk degeri bulunuz.


In [48]:
g = np.linspace(0,1)
g

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [49]:
g.mean()

0.5

In [50]:
g.std()

0.2945075446869757

In [51]:
g.var()

0.086734693877551

In [52]:
np.median(g)

0.5

In [53]:
g.min()

0.0

In [54]:
g.max()

1.0

27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.


* numpy arrayde yanlizca sayisal degerler yer alir. Seriler de ise her turlu veri tipi bulunabilir.

28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [55]:
t = pd.Series(np.arange(6), index=['A','B','C','D','E','F'])
t

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64

29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)


In [56]:
countries = {
    "Canada":"Ottowa",
    "USA":"Washington",
    "Turkey":"Ankara",
    "UK":"London",
    "Netherlands":"Amsterdam",
    "Germany":"Berlin",
    "Italy":"Rome"
}

df_countries = pd.Series(countries)
df_countries

Canada             Ottowa
USA            Washington
Turkey             Ankara
UK                 London
Netherlands     Amsterdam
Germany            Berlin
Italy                Rome
dtype: object

30.	10 elemanli random bir vektor olusturun.
* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.


In [57]:
y = np.random.randint(20, size=10)
y_series = pd.Series(y, index=["a","b","c","d","e","f","g","h","i","j"])
y_series

a     2
b    12
c     6
d     9
e    18
f    18
g     5
h    16
i    13
j    19
dtype: int64

In [58]:
y_series["c"]

6

In [59]:
y_series[0]

2

In [60]:
y_series[["b", "g"]]

b    12
g     5
dtype: int64

In [61]:
y_series["b":"g"]

b    12
c     6
d     9
e    18
f    18
g     5
dtype: int64

In [62]:
y_series[3:]

d     9
e    18
f    18
g     5
h    16
i    13
j    19
dtype: int64

31.	2 adet 5 elemanli seri olusturun.
* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.


In [63]:
v = pd.Series(np.arange(10,51,10))
y = pd.Series(['a','b','c','d','e'])
print(y,v)

0    a
1    b
2    c
3    d
4    e
dtype: object 0    10
1    20
2    30
3    40
4    50
dtype: int64


In [64]:
z = pd.concat([v,y])
z.index = range(1, len(z)+1)
z

1     10
2     20
3     30
4     40
5     50
6      a
7      b
8      c
9      d
10     e
dtype: object

In [65]:
z.loc[4:7]

4    40
5    50
6     a
7     b
dtype: object

In [66]:
z.iloc[4:7]

5    50
6     a
7     b
dtype: object

### Master odev ; 
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin.
Ve fark matrisinin diagonali,  -0.1 ile 0.1  arasinda olana kadar bu islemi tekrarlayin.
Istenilen matris bulundugunda program dursun ve  toplam kac dongunun kuruldugunu,  ne kadar sure icinde buldugunu ve  istenilen  matrisi  print ile birlikte ekrana yazdiriniz...
Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.


In [67]:
import time

In [79]:
def create_random_matrix(num_din = 20):
    print("Number of diagonals : ", num_din)
    start_time = time.time()
    loops = 0
    while True:
        matrix1 = np.random.rand(num_din,num_din)
        matrix2 = np.random.rand(num_din,num_din)
        diag = matrix1-matrix2
        diag_array = diag.diagonal()
        loops += 1
        if (diag_array > -0.1).all() & (diag_array < 0.1).all():
            break
            
    end_time = time.time()
    time_diff = end_time - start_time
    print(diag_array)
    
    print(f"It took {time_diff} seconds to finish the loop and found the value in {loops} step.")

In [89]:
create_random_matrix(10)

Number of diagonals :  10
[-0.04993383  0.05565994  0.01094268  0.04606167  0.09543383 -0.09438947
 -0.01516381 -0.08738321 -0.08820057 -0.02731363]
It took 229.15670585632324 seconds to finish the loop and found the value in 16463859 step.
