In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [ ]:
#1 vektor: tek boyutlu bir array dir. matris: cok boyutludur. En az ic ice 2 array icerir.

In [5]:
#2 
x = np.array([1,3,5,7,9,11,13,15,17,19])
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
#3 
y = np.zeros((10,10), dtype='int32')
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [7]:
#4 
z = np.ones((10,10), dtype='float')
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
#5
a = np.full((10,10),9, dtype='int32')
a

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)

In [9]:
#6
b = np.arange(5,25,3)
b

array([ 5,  8, 11, 14, 17, 20, 23])

In [10]:
#7
c = np.linspace(-1,1,30)
c

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [11]:
#8
d = np.random.randint(0,30,size=(5,6))
d

array([[ 1,  8,  0, 26, 21, 10],
       [17, 18, 14, 15, 25, 27],
       [23, 25, 12,  2,  6, 19],
       [ 3, 20,  6,  9,  9,  2],
       [15, 21, 13, 11, 10,  0]])

In [12]:
#9
e = np.eye(10)
e

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
#10
f = np.random.randint(0,10,size=(5,10))
print(f)
print(f.size)
print(f.ndim)
print(f.shape)
print(f.dtype)

[[4 3 6 2 4 4 1 8 7 0]
 [4 6 2 1 3 0 4 5 7 5]
 [4 2 3 0 3 9 9 6 9 3]
 [9 4 0 0 9 5 8 2 5 5]
 [1 1 0 6 7 6 1 2 8 7]]
50
2
(5, 10)
int64


In [14]:
#11
g = np.random.randint(0,10,size=(3,4,7))
g

array([[[8, 3, 0, 6, 9, 2, 4],
        [2, 6, 8, 5, 1, 5, 4],
        [0, 1, 5, 9, 1, 9, 6],
        [2, 2, 7, 0, 2, 9, 3]],

       [[6, 0, 2, 4, 2, 8, 3],
        [3, 0, 0, 9, 2, 2, 6],
        [1, 9, 2, 7, 0, 3, 0],
        [5, 9, 0, 8, 9, 8, 1]],

       [[1, 2, 4, 0, 6, 0, 0],
        [2, 4, 2, 9, 3, 9, 1],
        [7, 7, 1, 7, 2, 3, 9],
        [8, 5, 0, 0, 8, 7, 1]]])

In [15]:
#12
h= np.arange(1,10)
print(h)
h1 = h.reshape(3,3)
print(h1)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#13
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.array([7,8,9])
x4 = np.array([10,11,12])
np.concatenate([x1,x2,x3,x4])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
#14
y1 = np.array([[56],[45]])

y2 = np.array([[6,9,3,4],
            [9,8,7,6]])

np.hstack([y1,y2])

array([[56,  6,  9,  3,  4],
       [45,  9,  8,  7,  6]])

In [ ]:
#15
# axis = 1 birlestirme islemini sutun olarak yapar. axis = 0 birlestirme islemini satir olarak yapar.

In [18]:
#16
z1 = np.array([[0,0,0],
              [9,9,9]])

z2= np.array([[8,8,8],
            [7,7,7],
             [6,6,6]])

np.vstack([z1,z2])

array([[0, 0, 0],
       [9, 9, 9],
       [8, 8, 8],
       [7, 7, 7],
       [6, 6, 6]])

In [19]:
#17
i1 = [67, 89,  43, 21, 34, 45, 87, 89, 12,  12]
np.split(i1,[2,5,6,7])

[array([67, 89]),
 array([43, 21, 34]),
 array([45]),
 array([87]),
 array([89, 12, 12])]

In [20]:
#18
j = np.random.randint(1,5000,size=5)
print(j)
j1 = np.sort(j)
print(j1)
print(j1[::-1])
for index, x in np.ndenumerate(j1):
  print(index, x)

[1220 4347  598 4955 3958]
[ 598 1220 3958 4347 4955]
[4955 4347 3958 1220  598]
(0,) 598
(1,) 1220
(2,) 3958
(3,) 4347
(4,) 4955


In [21]:
#19
k = np.random.randint(5000,size=20)
print(k)
f'3.eleman= {k[2]}  5.eleman= {k[4]}   7.eleman= {k[6]}'

[2942 4762 2706 4113 4337 1517  572 3285 4805 3386 3337 4349 2897 3945
  500 1236 3076  393 4774 3825]


'3.eleman= 2706  5.eleman= 4337   7.eleman= 572'

In [22]:
#20
l = np.random.randint(1,100,10)
print(l)
l[3]=87
print(l)

[73 58 11 86 80 24 67  9 82 58]
[73 58 11 87 80 24 67  9 82 58]


In [ ]:
#21

#Diagonal Matrix: Köşegen haric tüm item lerin sıfır olduğu bir matristir. 
#Trace of Matrix : Bir kare matrisin ana köşegenindeki elemanların toplamıdir.

In [23]:
#22
m = np.eye(5)
print(m)
print()
print(m[0,0],m[1,1],m[2,2],m[3,3],m[4,4])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

1.0 1.0 1.0 1.0 1.0


In [24]:
#23
n = np.arange(10,20)
print(n)
print(n[3::])

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17 18 19]


In [25]:
#24
p  = np.random.randint(56,size=(10,10))
print(p)
print(p[2])
print(p[:,4])
print(p[0:,[4]])
print(p[[1],0:])
print(p[3:7,0:10])
print(p[2:5,3:7])
print(p[5:,:4])
print(p[0:,[3,6,9]])
p[5,5]=1988
print(p)

[[17 33 11 55 21  3 54 26  3 31]
 [ 0 40  6 52 24  7  4 51 33 20]
 [53 45  1 35 38 31 50 14 18 35]
 [14 32  6  9 17 13 28 18 18 24]
 [10 50 51 43 35 45 31 37 19  8]
 [24  3 36  7 38 48 39 42 40 21]
 [23 13 46 34 10 46 48 34 32 24]
 [13 38 14 28 20 42 32 44 41 11]
 [25 49 42  7  1  9 38 22 47 42]
 [48 39 30 27 31 32 38 31 54 34]]
[53 45  1 35 38 31 50 14 18 35]
[21 24 38 17 35 38 10 20  1 31]
[[21]
 [24]
 [38]
 [17]
 [35]
 [38]
 [10]
 [20]
 [ 1]
 [31]]
[[ 0 40  6 52 24  7  4 51 33 20]]
[[14 32  6  9 17 13 28 18 18 24]
 [10 50 51 43 35 45 31 37 19  8]
 [24  3 36  7 38 48 39 42 40 21]
 [23 13 46 34 10 46 48 34 32 24]]
[[35 38 31 50]
 [ 9 17 13 28]
 [43 35 45 31]]
[[24  3 36  7]
 [23 13 46 34]
 [13 38 14 28]
 [25 49 42  7]
 [48 39 30 27]]
[[55 54 31]
 [52  4 20]
 [35 50 35]
 [ 9 28 24]
 [43 31  8]
 [ 7 39 21]
 [34 48 24]
 [28 32 11]
 [ 7 38 42]
 [27 38 34]]
[[  17   33   11   55   21    3   54   26    3   31]
 [   0   40    6   52   24    7    4   51   33   20]
 [  53   45    1   35   38  

In [26]:
#25
r = np.arange(0,50,5)
print(r)
print(r[r>20].size)
print(r[r>30].size)
print(r[r==33].size)
print(r*5)
print(r%2)

[ 0  5 10 15 20 25 30 35 40 45]
5
3
0
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [27]:
#26
s = np.linspace(0,1,50)
print(s)
print(np.mean(s))
print(np.std(s))
print(np.var(s))
print(np.median(s))
print(np.min(s))
print(np.max(s))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
0.5
0.2945075446869757
0.086734693877551
0.5
0.0
1.0


In [ ]:
#27
#  pandas serileri farkli data typelari icerebilir.
#  numpy arrayler ayni data typelari icerebilir.

In [28]:
#28
t = pd.Series(["bulent","caliskan",'pyCoders',"class",4], index=('A','B','C','D','E'))
t

A      bulent
B    caliskan
C    pyCoders
D       class
E           4
dtype: object

In [29]:
#29
myDict = {'Turkiye':'Ankara','İrlanda':'Dublin','Yunanistan':'Atina','Ukrayna':'Kiev','Arjantin':'Buenos Aires'}
print(myDict)
u = pd.Series(myDict)
print(u)

{'Turkiye': 'Ankara', 'İrlanda': 'Dublin', 'Yunanistan': 'Atina', 'Ukrayna': 'Kiev', 'Arjantin': 'Buenos Aires'}
Turkiye             Ankara
İrlanda             Dublin
Yunanistan           Atina
Ukrayna               Kiev
Arjantin      Buenos Aires
dtype: object


In [30]:
#30
v = np.random.randint(1,100,10)
print(v)
y = pd.Series(v, index=('a','b','c','d','f','g','h','j','k','l'))
print(y)

print(y['c'])
print(y[0])
print(y[['b','g']])
print(y['b':'g'])
print(y['d':])

[90 83 13 12 47 94 76 53 23 51]
a    90
b    83
c    13
d    12
f    47
g    94
h    76
j    53
k    23
l    51
dtype: int64
13
90
b    83
g    94
dtype: int64
b    83
c    13
d    12
f    47
g    94
dtype: int64
d    12
f    47
g    94
h    76
j    53
k    23
l    51
dtype: int64


In [31]:
#31
z1 = pd.Series([1,2,3,4,5])
z2 = pd.Series([6,7,8,9,0])
print(z1)
print(z2)
z3 = pd.concat([z1,z2])
print(z3)
z3.index=range(1,11)
print(z3)


0    1
1    2
2    3
3    4
4    5
dtype: int64
0    6
1    7
2    8
3    9
4    0
dtype: int64
0    1
1    2
2    3
3    4
4    5
0    6
1    7
2    8
3    9
4    0
dtype: int64
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
10    0
dtype: int64
