1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

2.	10 elemanli bir listeden NumPy Array’i olusturunuz.

In [5]:
liste=list(range(10))
liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
import numpy as np
np.array(liste)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [8]:
np.zeros((10,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4.	Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [9]:
np.ones((10,10),dtype='float')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [12]:
np.full((10,10),9,dtype='int')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [14]:
np.arange(6,25,3)

array([ 6,  9, 12, 15, 18, 21, 24])

7.	-1 ile 1 arasinda 30 adet Array olusturunuz.

In [15]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [17]:
np.arange(0,30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
  * eleman sayisini
  * boyut bilgisini/sayisini
  * satir X sutun bilgisini
  * veri tipini numpy metodlariyla yazdiriniz.

In [43]:
arr = np.random.randint(0, 10,50).reshape(5,10)
arr

array([[8, 6, 3, 1, 2, 9, 1, 5, 6, 7],
       [8, 5, 4, 8, 7, 0, 9, 3, 6, 6],
       [8, 6, 3, 9, 8, 2, 4, 0, 5, 0],
       [5, 7, 0, 9, 5, 2, 4, 0, 6, 9],
       [4, 8, 6, 9, 3, 1, 1, 6, 9, 4]])

In [32]:
arr.size

50

In [44]:
arr.ndim

2

In [31]:
arr.shape

(5, 10)

In [35]:
arr.dtype

dtype('int32')

11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 

In [36]:
arr = np.random.randint(0, 10,3*4*7).reshape(3,4,7)
arr

array([[[1, 1, 7, 9, 2, 7, 9],
        [4, 1, 0, 3, 3, 2, 6],
        [5, 0, 3, 9, 9, 9, 5],
        [6, 7, 3, 7, 0, 1, 7]],

       [[3, 1, 2, 4, 2, 3, 1],
        [6, 8, 8, 0, 8, 6, 3],
        [7, 6, 4, 4, 1, 2, 2],
        [0, 3, 0, 5, 1, 7, 7]],

       [[4, 4, 4, 4, 1, 4, 9],
        [5, 9, 8, 7, 1, 8, 9],
        [4, 1, 9, 9, 0, 6, 5],
        [0, 6, 1, 7, 4, 2, 0]]])

12.	Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [38]:
arr = np.random.rand(12)
arr

array([0.09799137, 0.86953465, 0.66071666, 0.4254942 , 0.13921171,
       0.65906065, 0.06903198, 0.22157082, 0.3676481 , 0.4897588 ,
       0.15974621, 0.20620062])

In [40]:
arr.reshape(6,2)

array([[0.09799137, 0.86953465],
       [0.66071666, 0.4254942 ],
       [0.13921171, 0.65906065],
       [0.06903198, 0.22157082],
       [0.3676481 , 0.4897588 ],
       [0.15974621, 0.20620062]])

13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [42]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
k = np.array([10,11,12])
np.concatenate([x, y, z, k])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [47]:
arr1 = np.arange(0,12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
arr2 = np.arange(100,112).reshape(3,4)
arr2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [51]:
np.concatenate([arr1,arr2],axis=1)

array([[  0,   1,   2,   3, 100, 101, 102, 103],
       [  4,   5,   6,   7, 104, 105, 106, 107],
       [  8,   9,  10,  11, 108, 109, 110, 111]])

15.	Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  

16.	Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [85]:
arr1 = np.arange(0,5)
arr1

array([0, 1, 2, 3, 4])

In [96]:
arr2 = np.arange(-20,0).reshape(4,5)
arr2

array([[-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1]])

In [87]:
np.vstack([arr1,arr2])

array([[  0,   1,   2,   3,   4],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1]])

In [97]:
np.hstack([arr1.reshape(5,1),arr2.T])

array([[  0, -20, -15, -10,  -5],
       [  1, -19, -14,  -9,  -4],
       [  2, -18, -13,  -8,  -3],
       [  3, -17, -12,  -7,  -2],
       [  4, -16, -11,  -6,  -1]])

17.	10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

In [98]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [105]:
v = np.random.randint(0,10,15)
v

array([8, 5, 8, 6, 3, 4, 3, 8, 8, 1, 4, 1, 1, 7, 2])

In [108]:
v_sorted = np.sort(v)[::-1] 
v_sorted

array([8, 8, 8, 8, 7, 6, 5, 4, 4, 3, 3, 2, 1, 1, 1])

In [111]:
for i in range(len(v_sorted)):
    print(f'{i}.indexte {v_sorted[i]} var')

0.indexte 8 var
1.indexte 8 var
2.indexte 8 var
3.indexte 8 var
4.indexte 7 var
5.indexte 6 var
6.indexte 5 var
7.indexte 4 var
8.indexte 4 var
9.indexte 3 var
10.indexte 3 var
11.indexte 2 var
12.indexte 1 var
13.indexte 1 var
14.indexte 1 var


19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [113]:
n = np.random.randint(0,100,20)
n

array([41, 58, 59,  3, 15, 70,  0, 96, 40,  2,  8, 21,  3, 40, 31, 38, 47,
        2, 54, 18])

In [114]:
n[3], n[5], n[7]

(3, 70, 96)

20.	10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.

In [116]:
m = np.random.randint(0,50,10)
m

array([16, 32, 16, 35, 22,  2, 12, 10,  8, 15])

In [118]:
m[4]=999
m

array([ 16,  32,  16,  35, 999,   2,  12,  10,   8,  15])

21.	“Diagonal Matrix” ve “Trace of Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

22.	5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [124]:
x = np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [126]:
x[0,0],x[1,1],x[2,2],x[3,3],x[4,4],

(1, 2, 3, 4, 5)

23.	10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [131]:
v = np.linspace(10,20,11)
v

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [132]:
v[3:]

array([13., 14., 15., 16., 17., 18., 19., 20.])

24.	10X10 luk bir matris olusturunuz ve ;
* 5.satir ve 5.sutuna ulasiniz.
* sutunun tum satirlarina ulasiniz.
* Tum sutunlarin 2.satirlarina ulasiniz.
* tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
* satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
* satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
* sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
* 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 

In [297]:
mat = np.random.randint(0,1000,100).reshape(10,10)
mat

array([[575, 146, 334,  53, 221, 881, 388, 914, 114,  89],
       [260, 797, 347, 527, 575, 225, 416, 673, 812, 767],
       [469, 224, 220, 812, 803, 663, 534, 239, 245, 951],
       [ 82, 513, 452, 578, 189, 745, 465, 257, 308, 422],
       [974, 953, 312, 709, 661, 628, 508, 972, 519, 637],
       [193, 614, 348,  53,  13, 866, 367,  60, 540, 914],
       [240, 346, 295, 230, 694, 782, 150, 989, 224,  55],
       [675, 814, 966, 696, 964, 549, 322, 744, 530, 693],
       [842, 312, 190, 820, 134, 228, 501, 411,  17, 519],
       [624, 690, 956,  13, 791, 593, 311,  74, 411, 427]])

In [298]:
mat[5,5]

866

In [299]:
mat[:,5]

array([881, 225, 663, 745, 628, 866, 782, 549, 228, 593])

In [300]:
mat[2,:]

array([469, 224, 220, 812, 803, 663, 534, 239, 245, 951])

In [301]:
mat[2:7,:]

array([[469, 224, 220, 812, 803, 663, 534, 239, 245, 951],
       [ 82, 513, 452, 578, 189, 745, 465, 257, 308, 422],
       [974, 953, 312, 709, 661, 628, 508, 972, 519, 637],
       [193, 614, 348,  53,  13, 866, 367,  60, 540, 914],
       [240, 346, 295, 230, 694, 782, 150, 989, 224,  55]])

In [302]:
mat[2:5,3:7]

array([[812, 803, 663, 534],
       [578, 189, 745, 465],
       [709, 661, 628, 508]])

In [303]:
mat[5:,:4]

array([[193, 614, 348,  53],
       [240, 346, 295, 230],
       [675, 814, 966, 696],
       [842, 312, 190, 820],
       [624, 690, 956,  13]])

In [304]:
mat[:,[3,6,9]]

array([[ 53, 388,  89],
       [527, 416, 767],
       [812, 534, 951],
       [578, 465, 422],
       [709, 508, 637],
       [ 53, 367, 914],
       [230, 150,  55],
       [696, 322, 693],
       [820, 501, 519],
       [ 13, 311, 427]])

In [305]:
mat[5,5]=1984

25.	0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
* 20 den buyuk olan kac deger var.
* 30’dan kucuk kac deger var
* icerisinde 33 gecen kac deger var
* olusturulan arrayin tum elemanlarini 5 ile carpin.
* olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
* olustural arrayin icerisinde, sadece sutunlara bakarak her bir sutunu toplayin ve toplami 30 dan buyuk kac sutun var
* olustural arrayin icerisinde, sadece satirlara bakarak her bir satiri toplayin ve toplami 30 dan buyuk kac satir var.

In [148]:
arr = np.arange(0,51,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [149]:
len(list(filter(lambda x: x>20, arr)))

6

In [150]:
len(list(filter(lambda x: x<30, arr)))

6

In [151]:
len(list(filter(lambda x: x==33, arr)))

0

In [152]:
arr*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250])

In [153]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

26.	0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
* orlamasini aliniz.
* standart sapmasini aliniz.
* varyansini aliniz.
* median’ini aliniz.
* en kucuk degeri bulunuz.
* en buyuk degeri bulunuz.

In [158]:
p = np.linspace(0,1)
p

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [159]:
p.mean()

0.5

In [160]:
p.std()

0.2945075446869757

In [161]:
p.var()

0.086734693877551

In [167]:
np.median(p)

0.5

In [165]:
p.max()

1.0

In [166]:
p.min()

0.0

27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

In [169]:
import pandas as pd
ser = pd.Series(data=np.arange(1,6), index=['A', 'B', 'C', 'D', 'E'])
ser

A    1
B    2
C    3
D    4
E    5
dtype: int32

29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

In [170]:
keys = ['France','China','UK','USA','Japan']
values= ['Paris','Beijing','London','Washington','Tokyo']
pd.Series(values,keys)

France         Paris
China        Beijing
UK            London
USA       Washington
Japan          Tokyo
dtype: object

30.	10 elemanli random bir vektor olusturun.
* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

In [175]:
v = np.random.randint(0,100,10)
v

array([51, 31, 49, 93, 78, 30, 16, 15, 55, 37])

In [179]:
list("abcdefghij")

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [181]:
ser = pd.Series(v, list("abcdefghij"))
ser

a    51
b    31
c    49
d    93
e    78
f    30
g    16
h    15
i    55
j    37
dtype: int32

In [191]:
ser['c']

49

In [192]:
ser['a']

51

In [195]:
ser[['b','g']]

b    31
g    16
dtype: int32

In [197]:
ser['b':'g']

b    31
c    49
d    93
e    78
f    30
g    16
dtype: int32

In [198]:
ser['d':]

d    93
e    78
f    30
g    16
h    15
i    55
j    37
dtype: int32

31.	2 adet 5 elemanli seri olusturun.
* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

In [201]:
ser1 = pd.Series(range(100,501,100))
ser1

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [202]:
ser2 = pd.Series(list('abcde'))
ser2

0    a
1    b
2    c
3    d
4    e
dtype: object

In [204]:
ser3 = pd.concat([ser1, ser2])
ser3

0    100
1    200
2    300
3    400
4    500
0      a
1      b
2      c
3      d
4      e
dtype: object

In [216]:
ser3.index=range(1,11)
ser3

1     100
2     200
3     300
4     400
5     500
6       a
7       b
8       c
9       d
10      e
dtype: object

### Master odev ; 
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin.
Ve fark matrisinin diagonali,  -0.1 ile 0.1  arasinda olana kadar bu islemi tekrarlayin.
Istenilen matris bulundugunda program dursun ve  toplam kac dongunun kuruldugunu,  ne kadar sure icinde buldugunu ve  istenilen  matrisi  print ile birlikte ekrana yazdiriniz...
Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [ ]:
import time
loop=0
t1=time.time()
while True:
    loop+=1
    matrix = [np.random.rand(20,20) for _ in range(2)]
    m1 = matrix[0]
    m2 = matrix[1]
    diag = abs(np.diag(m1-m2))
    if len(list(filter(lambda x: x>0.1, diag)))==0:
        break
t2=time.time()
time_diff = t2-t1

In [ ]:
loop

In [ ]:
time_diff

In [ ]:
diag

In [ ]:
list(filter(lambda x: x<0.1, diag))